### ISSUE TITLE
Create a github pages website 

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#10]
The website should contain:
- a download link to the recent apk
- step by step instal guide
- release note and version history

...feel free to extend this list

**Comment by fm-sys** [comment]
GitHub pages is now activated for providing information about the latest release...

See https://fm-sys.github.io/snapdrop-android/output-metadata.json

But still the graphical side needs to be done!

**Comment by itscodezada17** [comment]
hi ,
fm-sys , please tell me more about the changes you want , i'll happy to contribute. thank you

**Comment by fm-sys** [comment]
Thanks for your offer, very welcomed! 

I thought of a small webpage to introduce Snapdrop for Android, maybe including the playstore images and a localized version of the app description. The design should be simple and modern, and should fit to snapdrop.net / Snapdrop for Android. So probably a blue background and white text color... (Maybe even reusing the css from snapdrop.net?)

**Comment by fm-sys** [comment]
Probably, a own website is a bit too much work without real benefit. I suggest to rather improve the styling/content of the Readme... Let's close for now
