### ISSUE TITLE
Crashes with 'Aw, Snap!' when trying to save

### ISSUE THREAD

**Issue by Len-B** [fm-sys/snapdrop-android#118]
Crashes with 'Aw, Snap!' when trying to save.

This problem has just started after a recent Google Chrome update. When trying to transfer files from my PC to an Android device they appear to transfer but then the save fails.

Yesterday I overcame the problem by using MS Edge and all went well. Today my MS Edge also had an update and now that fails.

I then tried Firefox Quantum and that still works.

Thanks,

Len

**Comment by fm-sys** [comment]
Does transfer between your browsers (without android app) work normally? Could you provide a screenshot?

**Comment by Len-B** [comment]
Hi,

Thanks for the speedy reply.

I have sent 3 screenshots, all from my Android app, but they don't show much more than I've descibed.

I should have made it clear that the browser updates were on my Windows 10 Pro PC and both are now at the latest version.

I tried a browser to browser (PC Chrome to Android Chrome) transfer with the same result.

The progress circle completes it's full 360 and then there is a short hang before the 'Aw, Snap!' error occurs.

Reloading at both ends often results in loss of connection name at the PC end and sometimes duplicate names at the Android end.

Hope this help,

Len

![Screenshot_20210724-203729  File Received](https://user-images.githubusercontent.com/35223209/126879543-70c4aa0b-3a93-4714-bb3d-5c64c06e9abe.jpg)
![Screenshot_20210724-203736  Aw, Snap! Error](https://user-images.githubusercontent.com/35223209/126879544-3fc8f71a-13c3-4145-941e-635488a370a0.jpg)
![Screenshot_20210724-203609  Duplicates the Name](https://user-images.githubusercontent.com/35223209/126879545-e139f9f0-da31-46cd-931a-406ad42e2e2f.jpg)

**Comment by fm-sys** [comment]
Ah, I see. I cannot reproduce the "Aw, Snap!" exception but I see similar issues when trying to download something. Indeed, something seams to be quite buggy. 

However, as it seems to be not only related to the android app, it might be better to open an issue here:
https://github.com/RobinLinus/snapdrop/

When looking at their issue tracker, there already is an brand new issue which might be related to your observation:
https://github.com/RobinLinus/snapdrop/issues/331

**Comment by Len-B** [comment]
I'm confused. I thought this was the Snapdrop team and where I reported issues. What/who is https://github.com/RobinLinus/snapdrop/

**Comment by Len-B** [comment]
I've just realised - I believe this is just for the Android app.

**Comment by fm-sys** [comment]
> I've just realised - I believe this is just for the Android app.

Yes, correct. I believe we can close here...
