### ISSUE TITLE
Vibration alert 

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#123]
An option to alert user via phone vibration when the file transfer is complete.

**Comment by siva-subramaniam-v** [comment]
Should the device vibrate after both send and receive actions?

I can add this feature to the app. Can you assign this to me?

**Comment by fm-sys** [comment]
Initially I just thought about receive but probably both would make sense...

**Comment by fm-sys** [comment]
Implemented in #299
