### ISSUE TITLE
App Not Optimized?

### ISSUE THREAD

**Issue by gladel** [fm-sys/snapdrop-android#132]
I'm trying to install on the Onn 8" Tablet and states that the app may not be optimized for my device.

**Comment by ueen** [comment]
I guess this would be due to the large screen, no? i dont think it would need special optimizing though, does it look/work fine to you?

**Comment by fm-sys** [comment]
Probably, this happens due to a missing tablet screenshot:

https://stackoverflow.com/questions/47591281/google-play-says-this-app-may-not-be-optimized-for-your-device-when-i-access

**Comment by gladel** [comment]
Finally decided to install it, tested it, and noticed that after file transfer it does not initiate download.

**Comment by fm-sys** [comment]
Don't know how Google Play decides whether an app is optimized. But it shouldn't affect usability.

Download should work though, so if you still have problems please let me know...
