### ISSUE TITLE
App not working without valid https certificate 

### ISSUE THREAD

**Issue by dokeraj** [fm-sys/snapdrop-android#135]
**Describe the bug**
Error shows `Please verify that you are connected with a WiFi network`. I've setup a custom base url: `http://192.168.1.11:8800/` (this is on another machine on the same LAN), using the https://hub.docker.com/r/jarylc/snapdrop snapdrop docker image. 
Note that if I try to open the same url through firefox (on my android device), I can connect with the other machines on the same LAN, so I know for a fact that the error is in this app.

**To Reproduce**
1. Start a docker container with the following docker command `docker run -d --name snapdrop -e HTTP_PORT=8800 -e PORT=4100 -e SINGLE_ROOM=1 -e STUN_SERVER=stun:stun.l.google.com:19302 -p 4100:4100 -p 8800:8800 --restart unless-stopped minimages/snapdrop`
2. Open the `snapdrop-android` app and change the baseURL to `http://localhost:8800`
4. See error `Please verify that you are connected with a WiFi network`

**Expected behavior**
The app needs to show the screen where we can connect to other devices

**Smartphone (please complete the following information):**
 - Device: Poco F2 Pro
 - OS: custom ROM android 11

**Comment by fm-sys** [comment]
Do you have a valid HTTPS certificate registered for the URL? Otherwise this might be the problem... (Although I totally agree that it would be nice to have a possibility to get in anyway)

**Comment by dokeraj** [comment]
No, I don't have a certificate, but since I'm only using it on my local
network, I don't think that I would need it.

**Comment by fm-sys** [comment]
> since Android 9 Pie, requests without encryption will never work. And by default, the System will expect you to use TLS by default.You can read this feature here So if you only make requests via HTTPS you are safe.

But this can be configured in the manifest.

https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie

**Comment by dokeraj** [comment]
Yes, I know :)
I have this in the manifest of my app.

**Comment by dokeraj** [comment]
Hi,
Any new progress on this?

Cheers

**Comment by dokeraj** [comment]
I've tested with adding the following `android:usesCleartextTraffic="true"` in the _AndroidManifest.xml_ and now I can use the app with http requests. 

Can you also add this to the project please.

**Comment by fm-sys** [comment]
Cool! Do you want to open a PR?

**Comment by dokeraj** [comment]
Sure. I will close this issue now.
