### ISSUE TITLE
Can not use the custom host address.

### ISSUE THREAD

**Issue by CDLLY** [fm-sys/snapdrop-android#140]
It works without setting, but after I replace the default host address, it just shows me a blank...
You know, if we use our own snapdrop server, it means we can transfer files in WWW, not only the LAN, so fix it, please.🙏

![S11124-16165511](https://user-images.githubusercontent.com/20614068/143202100-b151895f-944d-4ff0-af69-00d1f31347f7.png)

 And I have a valid HTTPS certificate from Zerossl, snapdrop works fine in web.

**Comment by fm-sys** [comment]
Can you please tell which custom URL you have entered? Maybe there are some problems if the URL is formatted in a different way than expected...

**Comment by fm-sys** [comment]
Hi,

I will close the issue for now, due to the lack of necessary information. Feel free to comment if you have more details... Will reopen the issue as soon as I can reproduce it.
