### ISSUE TITLE
Snapdrop fails on Samsung Galaxy A7 Lite (SM-T220)

### ISSUE THREAD

**Issue by hariseldon99** [fm-sys/snapdrop-android#146]
**Describe the bug**
Snapdrop fails to send or receive files from any other device on the network, running via app or browser.
All VPNs and ad-blockers running on the tablet were disabled during the attempted transfer.

**To Reproduce**
1. Open browser to snapdrop.net on both A7 lite and any other device connected to the same LAN
2. Try to transfer any data from other device to A7 lite

***Error Message in Developer Console***
network.js:333 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:333
(anonymous) @ network.js:289
Promise.catch (async)
onServerMessage @ network.js:289
_onMessage @ network.js:378
(anonymous) @ network.js:367
fire @ network.js:509
_onMessage @ network.js:39
ws.onmessage @ network.js:19

**Expected behavior**
Data should transfer, as it does between all other devices.

**Screenshots**
![Screenshot from 2021-12-06 11-50-17](https://user-images.githubusercontent.com/10812394/144797565-d6e013b2-4730-42e2-b7c9-4ada9de21197.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.3 LTS
 - Browser Chrome
 - Version 96.0.4664.45 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy SM-T220
 - OS: Android 11 (One UI Core version 3.1) Kernel 4.19.127-22351182 Build No: RP1A.200720.012.T220XXU1AUJ1
 - Browser Chrome
 - Version 96.0.4664.45

**Comment by fm-sys** [comment]
Does it work with different devices in your network or is it a more generic problem?

**Comment by hariseldon99** [comment]
It works between all other device pairs in the network except for the tablet.

**Comment by fm-sys** [comment]
The exception looks quite similar to https://github.com/RobinLinus/snapdrop/issues/345

Probably the issue needs to be fixed on their side...

**Comment by hariseldon99** [comment]
Ok, I'm gonna watch that thread.
