### ISSUE TITLE
Two Android devices on same network have same name 

### ISSUE THREAD

**Issue by katchy3132** [fm-sys/snapdrop-android#148]
**Describe the bug**
When two Android devices are on the same network and want to share a file with each other they are both given the same name. THis confuses the app so even if a Windows machine joins the group it cant send to either. Just the two Android by themselves cannot send to each other but one Android and one Windows can send to each other . When all three are on usually the two androids show the other android plus windows (And cant send to either). In such a case the Windows will sometimes show neither or possibly one Android device (the second one to open) but will never show both android devices. 

**Expected behavior**
Able to transfer between all devices. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3707138/145709377-bb0a61eb-3383-492c-ba0b-0c0660b1b53d.png)

![image](https://user-images.githubusercontent.com/3707138/145709464-513cd8e3-8a7c-429c-9860-89d3a050bf13.png)

**Desktop (please complete the following information):**
Windows 10 Chrome 96

**Smartphone (please complete the following information):**
Poco F3 Android 11
Redmi Note 5 Android 9

**Comment by katchy3132** [comment]
possibly related to #97

**Comment by fm-sys** [comment]
Wow, this is strange 😅

Does this happen regularly or was it more a one-time-problem?

**Comment by katchy3132** [comment]
Clearing data on one device seems to have fixed it 😁
I got a new device and it must have copied the settings (and cached name) via Android settings backup.

maybe stick this in a FAQ somewhere ....
