### ISSUE TITLE
Try local IP if both devices use the android app

### ISSUE THREAD

**Issue by szaimen** [fm-sys/snapdrop-android#150]
Hello, 

in my tests is snapdrop unfortunately pretty slow because it transfers the files over the router and doesn't use the local ip-address to transfer the files, as far as I understand it.

I suppose that using the local ip-address when both are using the android app would speed up the transfer by a lot.

This could by implemented like a try catch method: try to transfer the file from local to local ip-address. If the connection attempt fails, simply use the standard method instead.

Thanks for considering!

**Comment by fm-sys** [comment]
> it transfers the files over the router and doesn't use the local ip-address

It does use the local WiFi network. The files will never leave your private home network. But you cannot transfer files without being in the same WiFi network (connected to the same router), so I don't really get your point...

> try to transfer the file from local to local ip-address

Something like this does not exist in the may you might expect it. The only thing which is theoretically possible is _WiFi Direct_ which however will be really hard (impossible?) to implement as snapdrop is cross-platform...

**Comment by szaimen** [comment]
> It does use the local WiFi network. The files will never leave your private home network.

Okay, then I don't understand why the transfer is so slow. Both devices I was testing it with were connected to the Wi-Fi AP with almost 500 mbit/s so it should in theory be able to transfer with at least 30 MB/s but the transfer speed in my test was closer to 3-4 MB/s...

**Comment by fm-sys** [comment]
> Okay, then I don't understand why the transfer is so slow. 

That's a good question. Many others have asked this as well (including myself)

You can read more about it here:
https://github.com/RobinLinus/snapdrop/issues/123
