### ISSUE TITLE
Bromite webview incopatibility

### ISSUE THREAD

**Issue by Warden20** [fm-sys/snapdrop-android#163]
**Describe the bug**
On my phone I use linageos 18.1 and the application was working fine until I installed bromite webview. Is there any solution or why is this happening?
The application does not recognize devices and if it does it is only for a second without sending information.

**Smartphone (please complete the following information):**
 - Device: poco x3 nfc
 - OS: Linageos 18.1 android 
 - Browser bromite
 - Version android 11
-  snapdrop 1.9.0 from fdroid

**Comment by fm-sys** [comment]
Bromite does block many browser APIs for privacy reasons. Haven't looked deeper into it yet, but I guess Snapdrop needs one of those to work properly.

What also happened from time to time:
Snapdrop does not work for some reason, if specific Ad-blockers are turned on. So disabling the build in Ad-blocker of Bromite for this app could also work.

Unfortunately, I will most likely not have the time to work on this issue as the potential User groop for bromite isn't really large. But I would be happy if your able to finally find any solution for other bromite users...

**Comment by DodoLeDev** [comment]
Hi!
I have the same problem, and it's really limitating!
I'm forced to use a browser like Firefox, and then I lose the ability to _share to Snapdrop_ from any application!

A simple workaround would be **integrating an appropriate Webview into the app package** ! It increases the size, but is only aimed to Bromite users!

_The only problem is that I don't know how to do it!_  :sweat_smile:

**Comment by fm-sys** [comment]
@DodoLeDev Thanks for the link! A fix was already merged on their side, so we only have to wait until they make a new release... 

https://github.com/bromite/bromite/issues/1693

**Comment by DodoLeDev** [comment]
Yeah! I will finally be able to re-use this incredible app instead of the website! :muscle:

**Comment by fm-sys** [comment]
Bromite has done a new release, `v98.0.4758.116`. Can somebody check whether the situation has changed?

**Comment by DodoLeDev** [comment]
Yeah! We can detect other devices as expected! BUT, we still cannot send and receive files or even messages...
This issue is just partially fixed...

**Comment by fm-sys** [comment]
OK, this matches to the experience described in https://github.com/bromite/bromite/issues/1693. Let's hope they continue to work on that issue...
