### ISSUE TITLE
Properly color the navbar

### ISSUE THREAD

**Issue by AnonWombat** [fm-sys/snapdrop-android#172]
**Expected behavior**
The background of the navbar should be the same color as the rest of the app and follow the correct theme.

**Screenshots**
![Screenshot_20220207-122703_Snapdrop](https://user-images.githubusercontent.com/44946401/152840611-6176d08f-7086-457b-8bfa-790c56a56e7c.png)

In the photo above, the background of the navbar should be white.

Here's an example from TwidereX:
![Screenshot_20220207-123146_Twidere X](https://user-images.githubusercontent.com/44946401/152840950-1d49f9ec-f37c-48a8-b182-0232c8089813.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 12

**Comment by fm-sys** [comment]
Fixed with https://github.com/fm-sys/snapdrop-android/commit/eac12596a2ac51d2fa844cbe9d5f6dc25e271068
