### ISSUE TITLE
Connection lost retry in 5 seconds

### ISSUE THREAD

**Issue by Fehertukor** [fm-sys/snapdrop-android#176]
Thank you for your work I really love Snapdrop!

**Describe the bug**
When I enter in the snapdrop android app I get this message(started about from last week):
Connection lost retry in 5 seconds
It has worked in the past 1000 times...
PC can't reach official site too.
Internet works wifi works.

**To Reproduce**
It is the same everytime.

**Expected behavior**
To see the other computer or phone and send file.

 1.9.3 Android Snapdrop version

**Comment by fm-sys** [comment]
Yes, this is true unfortunately. First of all, thanks for opening a ticket instead of writing a bad review on Google Play :) 

However, the Snapdrop.net website is not hosted myself, so the only thing I can do is to link you to this thread:

https://github.com/RobinLinus/snapdrop/issues/415

**Comment by Fehertukor** [comment]
Thank you again.
Yes it works for me too now!
