### ISSUE TITLE
easy server / base url change menu

### ISSUE THREAD

**Issue by Lud-a-Jak** [fm-sys/snapdrop-android#183]
### Describe the feature

In addition to using main server I have a snapdrop server running in docker container on my private network which sometime doesn't have internet access.
So anytime I want to change servers, I need to type in different address and port in Base URL. 
Instead of changing the Base URL by typing every time, it would be nice if it is possible to add "Server" menu in settings instead 
![image](https://user-images.githubusercontent.com/71732796/157431931-3eafaac2-ba7e-42a2-b14a-0f1b54165b74.png)
with ability to add presets in form of 
![image](https://user-images.githubusercontent.com/71732796/157432070-f038ee42-8cfe-46b1-9845-da461b8bef34.png)
or
![image](https://user-images.githubusercontent.com/71732796/157432854-a26c2987-8a4a-427c-971c-0160c61f151a.png)

### Describe alternatives you've considered

*

**Comment by fm-sys** [comment]
Sounds understandable. Maybe this setting could also be opened additionally when long clicking on the settings icon. Just thinking... ;-)

**Comment by Lud-a-Jak** [comment]
Sure, why not.
Or put a separate additional button on the main screen, maybe so it is easier to find, which ever is easier to implement. 😊

**Comment by Lud-a-Jak** [comment]
Maybe also make the default server preset "https://snapdrop.net" unable to delete/remove, unlike custom ones, so that one does not delete it by mistake

**Comment by fm-sys** [comment]
I just added a shortcut to access the server selection by clicking on the URL inside the actionbar. However, no custom presets yet...
