### ISSUE TITLE
Add Material You design

### ISSUE THREAD

**Issue by nsengupta5** [fm-sys/snapdrop-android#184]
### Describe the feature

This feature is mainly to incorporate the new Material You design compatible for Android 12. It would offer a new type of design that can be toggled on or off in the settings based off the user's preference. The new design will use the user's wallpaper to determine the color scheme of the app.

### Describe alternatives you've considered

None except to keep the current design.

**Comment by ueen** [comment]
This would only affect the top bar, as the heart of the app really just is a webview of the website (which onky has light/dark mode).
Feel free to try though and create a PR :)

**Comment by fm-sys** [comment]
Monochrome material you launcher icon might be interesting for some users and was implemented in #229, everything else doesn't really make sense IMHO.
