### ISSUE TITLE
"send via snapdrop" floating action target

### ISSUE THREAD

**Issue by raiden076** [fm-sys/snapdrop-android#195]
### Describe the feature

If by any chance, you could implement clipboard sync,
(Maybe be something like clipt, but that's a complete different backend) it would be perfect..! 

### Describe alternatives you've considered

Clipt is a decent one.
But far from perfect.

**Comment by fm-sys** [comment]
This was already requested in #109. Actually we didn't want to go that way, but users seem to really miss that feature 😅

**Comment by raiden076** [comment]
> This was already requested in #109. Actually we didn't want to go that way, but users seem to really miss that feature 😅

Maybe, using text files,
But I guess that's too much work, 
Anyway, thanks for developing this,
It's great,

P. S. You guys and your main project was featured in mrwhosetheboss today, cheers.

**Comment by fm-sys** [comment]
> P. S. You guys and your main project was featured in mrwhosetheboss today, cheers.

I've already heard of it. It's totally awesome! 

Thereupon Snapdrop has experienced such a huge user peak, that the servers had temporarily stopped working. (At least I guess, that the server outtake was caused by the huge traffic.) But meanwhile everything is running again smoothly :)

**Comment by fm-sys** [comment]
Snapdrop already supports sending text. (Just long-click on a device)

![grafik](https://user-images.githubusercontent.com/64581222/165110396-e99748ce-9554-440b-945d-ce02e084b5e5.png)


Furthermore, apps are able to register themselves as floating action target. So we could easily offer a "send via snapdrop" option. I'm however not 100% sure if we should make this optional only and whether it should be enabled by default...

![grafik](https://user-images.githubusercontent.com/64581222/165112986-c8358548-9b0a-44bc-ab2f-5edf09029769.png)


https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999

**Comment by fm-sys** [comment]
I took the freedom to rename the topic. Something else then that isn't possible on android, and wouldn't fit to snapdrop anyway.

What do you think? Would this be a good alternative?

**Comment by raiden076** [comment]
> I took the freedom to rename the topic. Something else then that isn't possible on android, and wouldn't fit to snapdrop anyway.
> 
> What do you think? Would this be a good alternative?

Copy selected text,
Send via snapdrop,
Perfect solution if it happens...!

**Comment by ueen** [comment]
Thats a good idea, also maybe we could add an "paste" button here
> ![grafik](https://user-images.githubusercontent.com/64581222/165110396-e99748ce-9554-440b-945d-ce02e084b5e5.png)

would save another long click for pasting :)

**Comment by fm-sys** [comment]
Sneek preview:

![grafik](https://user-images.githubusercontent.com/64581222/177426952-7ed3af55-173c-4d20-97b0-c46678b43d11.png)


![grafik](https://user-images.githubusercontent.com/64581222/177426670-dd9d62b9-f63c-4a42-a830-c796a7f307f0.png)

![grafik](https://user-images.githubusercontent.com/64581222/177426704-e3e5dbf5-4a82-47ff-b25c-23e62a631ff6.png)

![grafik](https://user-images.githubusercontent.com/64581222/177426772-012299f8-4c74-4fc7-bc4b-e0a1fae87c35.png)

**Comment by raiden076** [comment]
Sweet 🤩🤩
