### ISSUE TITLE
Add option to directly change server if website is down 

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#197]
### Describe the feature

From time to time snapdrop.net is down, which is inconvenient for users and leads to many bad Google Play reviews.

If the app is unable to reach https://snapdrop.net it could automatically redirect to a fallback server.

@Bellisario has created a node.js version of snapdrop, which can be found here:

https://node-snapdrop.herokuapp.com/

May we use this instance and is the server capable to handle larger traffic? 

### Describe alternatives you've considered

It needs to be decided if we want to inform the user or not.

Either this happens without user interaction, with the downside that sending files between two android apps will work but users will not know which webpage to open on Windows/Mac/IOS.

Or we show a dialog: "Snapdrop.net is currently unavailable. Do you want to use the fallback server https://node-snapdrop.herokuapp.com/ in the meantime?" 

### Additional context

Related to  #183

**Comment by ueen** [comment]
great idea!
i like the dialog, its telling the user whats up, another dialog sould then intruct the user to also type the new adress in the browser, maybe there could be a shortened url to make it easier :)

**Comment by asadm** [comment]
I would like to +1 this idea. snapdrop is down right now and has been for a few days now. 

I have spinned up a mirror which I plan to maintain and improve on. Can be added as a fallback option / mirror: airdope.io

**Comment by ueen** [comment]
@asadm thanks for the mirror @fm-sys i cant enter it in the app, says it doesnt seem to be an snapdrop instance (works in normal browser), any ideas?

**Comment by fm-sys** [comment]
I had implemented a very basic check whether the entered website can be accessed and is a fork of snapdrop. Currently, the only thing I do is to search whether the word snapdrop is contained anywhere inside the html. For sure, this can be replaced by a better algorithm. 

@asadm if you add a comment like `<-- snapdrop fork -->` to your HTML it should get possible to activate this website inside the Snapdrop for Android app. For sure, we need to check whether it correctly runs inside the app, cause website adoptions might break some app-specific js code.

**Comment by Bellisario** [comment]
@fm-sys I'm not a Java developer so I don't know if this can be made, but I can suggest to check if the Snapdrop class is present in the window object, because it is exposed.
In this way, I was able to detect Snapdrop in the original, mine and @asadm one.

> DevTools example below

![image](https://user-images.githubusercontent.com/72039923/185785504-c20cf52e-f2b5-4aab-9c0c-b277688c9ffc.png)

**Comment by asadm** [comment]
I have added a `<!-- snapdrop fork -->` to the HTML. Can you check now?

**Comment by fm-sys** [comment]
> I have added a `<!-- snapdrop fork -->` to the HTML. Can you check now?

I'm now able to set your website inside the app and sending files does work as expected. However, receiving files does not work. Some change seems to cause an incompatibility here...

**Comment by fm-sys** [comment]
Switching the server automatically isn't a good idea IMHO (although I had initially suggested it)

Still it would be nice to make switching the server more easy which is discussed in #183

Furthermore we show an info dialog if the server is down. We could directly link to the server switching page in these cases.
