### ISSUE TITLE
Opening/installing apk file is no longer possible

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#200]
### Checklist

- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated "Snapdrop for Android" to the latest version. The bug is reproducible on this latest version.
- [X] I have checked, that this is NOT a general Snapdrop bug. It is only related to the Android app, and not reproducible with the website as well.

### App version

v1.10.1

### Android version

10

### Describe the bug

Apk files can no longer directly be installed

### Steps to reproduce the bug

- send an apk-file
- save it
- click open

Result: "No app can be found to open this file"

### Screenshots and additional context

Either we fix the bug or we remove the  android.permission.REQUEST_INSTALL_PACKAGES permission...

**Comment by ueen** [comment]
i feel like the fileending is kind of stripped, if you readd (rename) ".apk" in file explorer it works after enablening other sources.
I'm not sure wheter this is a new security feautre from google though (which would be annoying)
