### ISSUE TITLE
In-App option for taking temporary pictures, videos and audio recordings

### ISSUE THREAD

**Issue by thrdroom** [fm-sys/snapdrop-android#205]
### Describe the feature

When clicking a client to send a file to, please let the user select an option to take quick temporary fotos, videos or audio-recordings, inside the app just for sending to a client, without saving it to the gallery.

It would be nice if the temporary fotos and videos would use the dedicated camera app. As an alternative to the dedicated app, an in-app camera would also work, although it would be more limited i guess.

Maybe you could even consider a **"continuous shooting mode"**, where snapdrop connects to a client and holds the connecttion while opening a permanent camera interface, and continuously automatically sends every foto and video that has been shot to the client it is connected to, until the user exits the **"continuous shooting mode"**.

### Describe alternatives you've considered

The alternative and slower route is:

1. closing snapdrop
2. opening camera app
3. taking a foto/video
4. closing the camera app
5. opening snapdrop
6. sending the file to a client
7. closing snapdrop
8. opening the gallery app
9. deleting the foto/video

### Additional context

Snapdrop should make it easy for the user to simply shoot/record some fotos,videos or audios for quickly sending them to a client without having to switch apps and manage all the files when they are only meant to be temporary.

**Comment by ueen** [comment]
Not really sure this is a good idea, i feel like the app should just make it easier to share stuff, not add features to snapdrop.
Also the built in camera is probably best anyway. 
Maybe theres a way in which a system chooser could utilized to open the standard camera app and take a picture to share (the chooser would open on clicking on the device, now its straight opening files), could you look up what chooser/intent would be necessary to have the files app show up, as well as the pictures and/or camera app?

**Comment by thrdroom** [comment]
No, i don't talk about using a phone as a webcam. DroidCam is not the solution to what i asked for. I'm asking for a faster way to shoot and share Fotos fast with other clients. :)

**Comment by fm-sys** [comment]
I haven't found anything but maybe there is a camera app which registers itself as SAF file provider (like Google drive does in the example image below). 

If such an app doesn't exist yet someone could write one. Would be really appreciated, however doesn't have anything to do with this app. 

I'll close this issue, as adding the option to choose between camera and files would add one extra click. Sorry! 

![img](https://developer.android.com/static/images/providers/storage_picker.svg)
