### ISSUE TITLE
EXIF data stripped while sharing pictures 

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#211]
### Checklist

- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated "Snapdrop for Android" to the latest version. The bug is reproducible on this latest version.
- [X] I have checked, that this is NOT a general Snapdrop bug. It is only related to the Android app, and not reproducible with the website as well.

### App version

1.10.1

### Android version

Android 12 (huawei device) 

### Describe the bug

From support:

My phone photos always include location meta data. This information about the location of the photo is lost when sent via Snapdrop. And I think that's a pity, because the location data is important to me.  

### Steps to reproduce the bug

The problem actually occurs preferentially when I share from the gallery via Snapdrop. 

If I choose the images directly within Snapdrop, it is better. However, it seems that when I then select from the gallery in Snapdrop, the data will not be taken again. 

### Screenshots and additional context

It might be caused by some of the recent "Android privacy features"

Starting with Android 10 (or 11?), apps need to explicitly specify that they want to receive Metadata.

So we explicitly need to opt-in to receive the EXIF data.

You can read more about it here:
- https://stackoverflow.com/questions/68442139/exif-location-data-removed-when-sharing-photo-via-intent
- https://developer.android.com/reference/android/provider/MediaStore#EXTRA_ACCEPT_ORIGINAL_MEDIA_FORMAT
- https://issuetracker.google.com/issues/128675076

**Comment by siva-subramaniam-v** [comment]
I'd like to work on this issue. Can you assign it to me?

**Comment by siva-subramaniam-v** [comment]
Thanks for assigning it to me. Can you review my [PR](https://github.com/fm-sys/snapdrop-android/pull/295)?
