### ISSUE TITLE
Support via WiFi Direct and local WiFi personal hotspot

### ISSUE THREAD

**Issue by ghost** [fm-sys/snapdrop-android#213]
### Describe the feature

I am always frustrated that Snapdrop does not support WiFi Direct and local WiFi personal hotspot.

I did just that.

1. Samsung Galaxy S21 (Android 12 and OneUI 4.1) and realme GT 2 (Android 12 and realme UI 3.0).

2. Turn on both Android devices and install Snapdrop app. (1.10.1)

3. Both Android devices have no SIM card.

4. Create a local WiFi personal hotspot from realme device.

5. The Samsung device connects to the local WiFi personal hotspot.

6. Open the Snapdrop app on both devices.

7. Nothing happens. It comes the message that should connect to WiFi.

Note:
The same problem also when I try to use WiFi Direct.

### Describe alternatives you've considered

There is no alternative. I am looking for a simple app that allows to send multiple files and folders simultaneously via WiFi Direct and via local WiFi personal hotspot (without SIM card and eSIM).

**Comment by fm-sys** [comment]
Snapdrop for Android is basically a wrapper for the https://snapdrop.net website. Cause websites don't have the necessary permissions to establish a WiFi direct connection, we can't implement WiFi direct in a cross platform compatible way.

Local WiFi personal hotspot is working with snapdrop already today. However, some devices seem to block the communication between each other via Hotspot WiFi so we cannot promise that it will work on every device.

**Comment by fm-sys** [comment]
Pairdrop.net supports "pairing", so you will be able to send files even if devices are not connected via the same WiFi network. Transfer might eat up the data flatrate through... Other than that, it won't be possible unfortunately

**Comment by raniesantos** [comment]
🪦 RIP
