### ISSUE TITLE
Dark mode for the first page

### ISSUE THREAD

**Issue by breaking-loss** [fm-sys/snapdrop-android#225]
When enabling dark mode the send screen should be also dark

**Comment by fm-sys** [comment]
@breaking-loss could you please explain which screen do you mean?

**Comment by breaking-loss** [comment]
> @breaking-loss could you please explain which screen do you mean?

It was an  issue in a previous version but I forgot to close the issue . sorry for the delay

**Comment by fm-sys** [comment]
Okay, thanks for the response :)
