### ISSUE TITLE
I wish there was a way to choose a name and not get a random one

### ISSUE THREAD

**Issue by Dec-35** [fm-sys/snapdrop-android#226]
Could we be able to choose a name so it's easier to tell what devices is which?

**Comment by fm-sys** [comment]
You can already set a name inside the settings. Admitted, this will however only change the sub-name, not the randomly generated main name...

**Comment by soymadip** [comment]
> You can already set a name inside the settings. Admitted, this will however only change the sub-name, not the randomly generated main name...

Now even sub name is not changed

**Comment by fm-sys** [comment]
If choosing pairdrop.net, you'll be able to choose your personal name... IMHO this should be sufficient
