### ISSUE TITLE
Stuck At Splash Screen if the instance is down

### ISSUE THREAD

**Issue by NaiveInvestigator** [fm-sys/snapdrop-android#227]
### Checklist

- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated "Snapdrop for Android" to the latest version. The bug is reproducible on this latest version.
- [X] I have checked, that this is NOT a general Snapdrop bug. It is only related to the Android app, and not reproducible with the website as well.

### App version

1.11.0

### Android version

6

### Describe the bug

When https://snapdrop.net/ is down, the app stays at the splash screen indefinitely. Adding a timeout after 20 secs or 1 min would fix this issue. As for a workaround for now is to disable WiFi and then enter the app  to change the server instance.

### Steps to reproduce the bug

1. Add an instance that is down.
2. Restart the app.

**Comment by fm-sys** [comment]
Actually, we have a "instance down" detection. However it doesn't seem to work correctly.
