### ISSUE TITLE
Material Design 3 for the app icon

### ISSUE THREAD

**Issue by rusa99ec** [fm-sys/snapdrop-android#228]
### Describe the feature

This app has saved me a lot of time that it deserves a shortcut in my home screen. I'd love to see the icon upgraded to match  other icons and the wallpaper.

### Describe alternatives you've considered

I dont think there is an alternative.

**Comment by fm-sys** [comment]
Documentation: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by fm-sys** [comment]
Fixed with https://github.com/fm-sys/snapdrop-android/pull/229
