### ISSUE TITLE
1.11.2 breaks file transfer

### ISSUE THREAD

**Issue by terrytw** [fm-sys/snapdrop-android#233]
### Checklist

- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated "Snapdrop for Android" to the latest version. The bug is reproducible on this latest version.
- [X] I have checked, that this is NOT a general Snapdrop bug. It is only related to the Android app, and not reproducible with the website as well.

### App version

1.11.2

### Android version

12

### Describe the bug

I have a WSA setup, with latest 1.11.2 from play store. The other end is chrome webpage.

Transferring from chrome to WSA fails, but it works the opposite way.

Switching back to F-droid 1.11.0 version fixes the issue. 

### Steps to reproduce the bug

See bug description.

since snapdrop.net is down, I used https://node-snapdrop.herokuapp.com/

**Comment by fm-sys** [comment]
But can't imagine how this is related.

**Comment by fm-sys** [comment]
Can you check v1.11.1 as well?

**Comment by terrytw** [comment]
Where can I find 1.11.1? Latest F-droid version is 1.11.0 while play store does not let me choose version.

**Comment by terrytw** [comment]
Never mind, I found it in your repo. 

1.11.1 works fine.

**Comment by terrytw** [comment]
Update: tested on an real android phone, android version 10.
It's the same behavior. So I guess not related to how microsoft implemented WSA. 

Also I would like to mention that the circular file transfer progress bar works, and the file save windows pop up as well, if it helps. It's just after hitting save, nothing happens. I suspect something wrong when saving it to android storage.

**Comment by fm-sys** [comment]
I think I've found the bug - thanks for reporting it! 

Do you want to test v1.11.3? The APK is part of https://github.com/fm-sys/snapdrop-android/commit/eb0a4076e167033c19d0ded51471bd7c64eca1ca, release is already uploaded to google play but might take some time to be rolled out...

**Comment by terrytw** [comment]
Yeah I tested it, it's fixed! Thank you!
