### ISSUE TITLE
Implement app sending

### ISSUE THREAD

**Issue by timleg002** [fm-sys/snapdrop-android#25]
This guy wants it, could be a cool feature, I can get around to implement it later [issue on the original snapdrop repo](https://github.com/RobinLinus/snapdrop/issues/197)

**Comment by fm-sys** [comment]
A contribution would be very appreciated! On the other hand I wonder if it really would be worth. There are other apps which are optimized for exactly this task.

I sometimes share Android apps myself using Snapdrop. This is my procedure:

With [this apk extractor (it's without ads)](https://play.google.com/store/apps/details?id=me.psycoder.apkextractor) I get the apk and than select the Snapdrop Android client (this repo) to share the apk with...

IMHO this is the fastest way which can be imagined and even if we would try it to implement something like this our selves, we couldn't do it nearly as well without converting Snapdrop to a pure apk sharing tool what it neither is nor should be. 

![Screenshot_20201215_215751_copy_432x936](https://user-images.githubusercontent.com/64581222/102272263-c6b22880-3f20-11eb-8fe9-b5021770bb33.jpg)

**Comment by Krrishdhaneja** [comment]
If it is written in JS then we can write same in react native. Isn’t this 
a good idea?

**Comment by timleg002** [comment]
We could do this easily, I'd say. It's just implementing a View (don't know which one), forming it via parsing the input of a shell command, and just grabbing the file. It's that easy.

We could also implement app sharing & installing from the web interface.

**Comment by fm-sys** [comment]
As no further feedback occurred, I would like to close this issue. The summary: Snapdrop simply is no APK extractor. You can use [this one](https://play.google.com/store/apps/details?id=me.psycoder.apkextractor) if you want (it's without ads). The resulting APK can then be sent like every other file via this app.

The complexity of an app doubles with each feature added and becomes more difficult to maintain, as each time a change is made, all functions must be checked to see if they still work. Therefore, the rule: features that are very complex but only help a very small user group shouldn't be added. As I spend my free time for development, I do not plan to ever implement an APK extractor into **Snapdrop for Android**... Sorry!

**Comment by timleg002** [comment]
Anyways, this app is kind of doomed from the start, as it's still online-based, rather than implementing the features from scratch, allowing it to function offline.
