### ISSUE TITLE
App crashes when sending large audio file (66mb) from Firefox 

### ISSUE THREAD

**Issue by Pentaphon** [fm-sys/snapdrop-android#26]
I connect from Firefox on the same Wifi network to my phone and send a 66MB .opus file. Everything seems to work fine until the transfer circle completes and then the app crashes and the file never makes it to my download folder. 

It seems to work fine with tiny text files, but a 66MB audio file is enough to crash the app. 

This is on a Moto G7 running Android 9 stock.

**Comment by fm-sys** [comment]
Unfortunately it is difficult to reproduce for me. If it's possible for you, it would be great if you could post a log of the crash. 

A log file can be generated with this app. However, the app must first be given the necessary rights via the ADB...
https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by fm-sys** [comment]
With 0.5 GB it now happened for me too. First the whole system UI stuck and then the app crashes. The problem is that the total file gets loaded into the RAM before storing. I will see what I can do...

**Comment by Pentaphon** [comment]
> The problem is that the total file gets loaded into the RAM before storing.

That's what I suspected, but it's also doing it for much smaller files like podcasts which are about 50-100mb.

I think once you get your app into Google Play and have access to their crash logging, you'll be able to make this app much more stable.
