### ISSUE TITLE
IP address as Base URL

### ISSUE THREAD

**Issue by LisaJackson24-2** [fm-sys/snapdrop-android#268]
### Describe the feature

It's too bad that can't specify your own, alternative address as the Base URL, for example, if you use your own Node.js server with a normal IP address.

Also, taking into account the fact that the official snapdrop.net server is often down, perhaps it is worth adding to the settings not only the Base URL, but also the Alternative URL, and a switch on the start page so that, if necessary, simply switch between them if one of them does not work. Also, if someone also uses their own server, it will reduce the load on the official snapdrop server a bit, without losing agility application itself, because you don't always have your own server running, so sometimes you will still use the snapdrop.net server, so it will be good to have the opportunity to switch between them very quickly in the application.

And those who do not need it will not specify the Alternative URL, accordingly, they do not need the switch on the start page either. Therefore, they will not see any visual change. In my opinion, this is not a bad innovation. But the ability to specify an IP address as a Base URL is simply a necessity.

### Describe alternatives you've considered

-

**Comment by fm-sys** [comment]
Have you tried to add a proper protocol to the IP?

e.g. `http://127.0.0.1` instead of `127.0.0.1`

**Comment by schlagmichdoch** [comment]
Can confirm ip addresses with and without ports work as the base URL when a protocol is specified: `http://127.0.0.1:3000`

**Comment by LisaJackson24-2** [comment]
> Have you tried to add a proper protocol to the IP?
> 
> e.g. `http://127.0.0.1` instead of `127.0.0.1`

Oh, thank you. If you specify the protocol, then everything works. Sorry to bothered you.

But please consider implementing an additional Alternative URL, because even now snapdrop.net is not responding 😔

**Comment by schlagmichdoch** [comment]
Probably it would also help if there was a hint with the requested format like: 'Set the base url including the protocol: `https://snapdrop.net/`, `http://192.168.2.178/`'
