### ISSUE TITLE
Please check F-Droid builds

### ISSUE THREAD

**Issue by crok** [fm-sys/snapdrop-android#289]
### Checklist

- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated "Snapdrop for Android" to the latest version. The bug is reproducible on this latest version.
- [X] I have checked, that this is NOT a general Snapdrop bug. It is only related to the Android app, and not reproducible with the website as well.

### App version

-

### Android version

I don't know

### Describe the bug

Hi,

Just wanted to let you know that it seems that on F-Droid the latest version is still 1.12.0 which has been added a month ago on 2023-02-18 and v2.0.0 (released a week ago) is still not available on F-Droid - and perhaps v2.0.1 won't be either.. I know that sometimes it takes 2..4 days but I guess now it's not simply "slow" but there's something wrong behind the scenes.

### Steps to reproduce the bug

Go to the [F-Droid page of Snapdrop here](https://f-droid.org/en/packages/com.fmsys.snapdrop/) and check the available builds.

**Comment by fm-sys** [comment]
I assume F-Droid is just slow these days... I'll keep an eye on it

**Comment by fm-sys** [comment]
Don't know why it took so long, but yesterday Version 2.0.0 (34) suddenly appeared inside F-Droid. Still waiting for Version 2.0.1 though...

**Comment by fm-sys** [comment]
Version 2.0.1 was skipped, version 2.0.3 is available to download though... It seems that F-Droid isn't able to catch up, but there is no problem on our side.
