### ISSUE TITLE
Dark mode ?

### ISSUE THREAD

**Issue by Krrishdhaneja** [fm-sys/snapdrop-android#29]
So, I have both the web app and android app of snapdrop but the web app is having a dark mode but this isn't having that even after I download the latest update.

**Comment by fm-sys** [comment]
At the website, the dark mode was implemented just two days ago. So please be patient a little more, the dark mode will come very soon 😉

Technical background:
The Android app uses an webview to display the Snapdrop UI. This displayed website is a fork of the original snapdrop repo, because some changes were needed for the Android app. I can update the UI "over the air" without needing to release a new version. 
To have such updates even quicker, I'm currently working on a automatical merge service via github actions for updating the fork. Therefore I will not update the fork manually myself, cause then I would not be able to test the github action any more...

**Comment by Krrishdhaneja** [comment]
Ya, over the air updates would be awesome as there would be no need to download the apk any more.

**Comment by Krrishdhaneja** [comment]
By the way is there any iPhone version of this app?

**Comment by fm-sys** [comment]
I personally don't use IPhone, Mac, etc. so this one is made as android-only app. But there is an IOS app made by someone else...

see https://github.com/RobinLinus/snapdrop/issues/208

**Comment by fm-sys** [comment]
> Ya, over the air updates would be awesome as there would be no need to download the apk any more.

Unfortunately that is not possible for everything. Snapdrop UI changes are possible through, but everything else needs updates furthermore...

But I'm thinking of uploading the app to Google Play to make updates easier (however I'll probably have to spend a bit of money on it)

**Comment by Krrishdhaneja** [comment]
Add a sponsorship button on the repo and tge pwople who would be interested in this project might sponsor you?

**Comment by Krrishdhaneja** [comment]
Are on the air updates avaliable on react native ?

**Comment by Krrishdhaneja** [comment]
Ya, @fm-sys they are available using codepush by microsoft

**Comment by fm-sys** [comment]
Unfortunately, I don't know anything about react native 😬

But AFAIK apps can only update external loaded content but not the apk itself

**Comment by Krrishdhaneja** [comment]
It means you still have to update the release on gh? BTW what is the AFAIK?

**Comment by fm-sys** [comment]
> It means you still have to update the release on gh?

Yes, for new commits in https://github.com/fm-sys/snapdrop-android/
No, for new commits in https://github.com/fm-sys/snapdrop/

AFAIK = As Far As I Know

**Comment by Krrishdhaneja** [comment]
So now should i close this?

**Comment by fm-sys** [comment]
Feel free to keep it open as a reminder for me 😉 
I will close it when everything is done...

**Comment by Krrishdhaneja** [comment]
👍 ok

**Comment by fm-sys** [comment]
The bot did his job the first time (see https://github.com/fm-sys/snapdrop/pull/7) and will update the fork twice a day if changes are available.

The startup animation currently looks a bit strange when dark mode is activated, but that's a bit more complicated and a new release version will be needed to fix this... I will create a follow-up issue!

**Comment by Krrishdhaneja** [comment]
Yeah the first Over The Air update !

**Comment by Krrishdhaneja** [comment]
@fm-sys why is the logo of your app different from that of @RobinLinus ?

**Comment by fm-sys** [comment]
Is it different? I think it depends on which OS you are using. The logo is taken from the original snapdrop repository.

The reason why I took this one is just personal taste...

**Comment by Krrishdhaneja** [comment]
Let me share you tge pic. Of the logo @fm-sys

**Comment by Krrishdhaneja** [comment]
![Screenshot_20201223-134754_One UI Home.jpg](https://user-images.githubusercontent.com/65185487/102975046-7b51d880-4525-11eb-8408-4ec54b439fca.jpg)

**Comment by Krrishdhaneja** [comment]
@fm-sys that's android OS

**Comment by Krrishdhaneja** [comment]
And @fm-sys I found that animation stops after sometimes in your as well as the web app of @RobinLinus

**Comment by Krrishdhaneja** [comment]
Here is a video 
<iframe src="https://onedrive.live.com/embed?cid=4561021D1C8024F6&resid=4561021D1C8024F6%21116&authkey=AHd0DTRS6C1mbLU" width="148" height="320" frameborder="0" scrolling="no" allowfullscreen></iframe>

**Comment by Krrishdhaneja** [comment]
Here is the link to video->
https://1drv.ms/v/s!AvYkgBwdAmFFdBkxlRxC9ZkCBbw

**Comment by Krrishdhaneja** [comment]
Here is the link to video
https://1drv.ms/v/s!AvYkgBwdAmFFdBkxlRxC9ZkCBbw

**Comment by Krrishdhaneja** [comment]
> The bot did his job the first time (see [fm-sys/snapdrop#7](https://github.com/fm-sys/snapdrop/pull/7)) and will update the fork twice a day if changes are available.
> 
> The startup animation currently looks a bit strange when dark mode is activated, but that's a bit more complicated and a new release version will be needed to fix this... I will create a follow-up issue!

Which workflow you setup for this @fm-sys ?

**Comment by fm-sys** [comment]
> And @fm-sys I found that animation stops after sometimes in your as well as the web app of @RobinLinus

Could you please address this issue to the original snapdrop repository? This is something which needs to be fixed there...

**Comment by fm-sys** [comment]
> @fm-sys that's android OS

You are right that I did not choose the android web app icon of snapdrop. On the one hand, to stand out from each other and on the other hand, because I more like the blue background 😉

**Comment by fm-sys** [comment]
> > The bot did his job the first time (see [fm-sys/snapdrop#7](https://github.com/fm-sys/snapdrop/pull/7)) and will update the fork twice a day if changes are available.
> > The startup animation currently looks a bit strange when dark mode is activated, but that's a bit more complicated and a new release version will be needed to fix this... I will create a follow-up issue!
> 
> Which workflow you setup for this @fm-sys ?

https://github.com/fm-sys/snapdrop/actions/runs/439225721/workflow

**Comment by Krrishdhaneja** [comment]
@fm-sys do you have experience in python?

**Comment by fm-sys** [comment]
> @fm-sys do you have experience in python?

In fact, for a long time it was the only programming language I knew (reasonably) well. The Snapdrop app was the first real project I programmed with Java from scratch.

 Why do you ask?

**Comment by Krrishdhaneja** [comment]
i was having some issues with tkinter

**Comment by Krrishdhaneja** [comment]
@fm-sys ?
