### ISSUE TITLE
APK for Google TV

### ISSUE THREAD

**Issue by redneckeyeball** [fm-sys/snapdrop-android#291]
I use your Snapdrop / Pairdrop on all my devices, works excellent for transfer between mac and android.
But on my Google TV (which is also android) your apk is not available. Can you please look into this ? This would be an amazing tool to sideload apk's onto the Android / Google TV
Thank you ! Let me know if you need me to test.

**Comment by redneckeyeball** [comment]
Manually sideloading the current regular apk works, but I can't get past the config. No way to reach the 'continue' button after the selection of the https//pairdrop.net server.

**Comment by fm-sys** [comment]
Hi @redneckeyeball, 

We won't make it in the Google TV App Store, as we can't meet the quality requirements for Android/Google TV. However, I've fixed the focus handling for you, so you should be able to pass the config again. 

[snapdrop_googletv.apk](https://github.com/fm-sys/snapdrop-android/files/11129711/snapdrop_googletv.zip)

It would be great if you could test the new APK and let me know whether it works! :)
