### ISSUE TITLE
Upload to Google Play

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#30]
To have an easier update process, better findability, crash reports in the play console and much more nice features it would make sense to upload the app to the play store.

I will ask @RobinLinus if it's ok for him...

**Comment by Pentaphon** [comment]
If you don't end up going with F-Droid, this is a must, so yes please!

**Comment by fm-sys** [comment]
_Snapdrop for Android_ is meanwhile available at [Google Play](https://play.google.com/store/apps/details?id=com.fmsys.snapdrop)
