### ISSUE TITLE
Add Greek Language Support on Crowdin.

### ISSUE THREAD

**Issue by sv1sjp** [fm-sys/snapdrop-android#308]
### Describe the feature

Add Greek Language Support on Crowdin. I can contribute on translating the application in Greek Language.

### Describe alternatives you've considered

Add Greek Language Support on Crowdin. I can contribute on translating the application in Greek Language.

**Comment by fm-sys** [comment]
I've just enabled the Greek language :)

**Comment by sv1sjp** [comment]
> I've just enabled the Greek language :)

Thank you :) , the Greek translation has been finished!!!
