### ISSUE TITLE
Webapp not active when opening app settings

### ISSUE THREAD

**Issue by glemco** [fm-sys/snapdrop-android#323]
### App version

2.2.2

### Android version

12

### Describe the bug

If I open the app settings, the pairdrop/snapdrop gets suspended and when I go back it reloads with a new name.
It would be nice to keep it running until I close the app, the app settings shouldn't stop the service.

### Steps to reproduce the bug

1. Open the app
2. Open the settings (gear icon)
3. Go back

**Comment by fm-sys** [comment]
At least for some settings, it is necessary to do a reload after changing a setting anyway. Thus closing as "won't fix".
