### ISSUE TITLE
ZeroSSL not recognized on custom instance

### ISSUE THREAD

**Issue by sochartgit** [fm-sys/snapdrop-android#330]
### App version

2.2.3

### Android version

11

### Describe the bug

I'm running a pairdrop instance on docker with a custom ZeroSSL certificate.
I have a DNS rewrite in my DNS server to point pd.xxxx.com to my local ip address.

Android app accepts to validate the custom server in http, not in https.
It works perfectly fine in https on computer browsers (FF, Edge and Chrome).

If I access the same server behind a Cloudflare Zero Trust tunnel, it works beautifully in https. Same server, same settings, only the cert is different.

That's why I believe there's a bug validating ZeroSSL certs on android app only.

### Steps to reproduce the bug

Run your own instance of pairdrop with ssl from Let's encrypt or ZeroSSL
Run Android app and add your instance in https.

**Comment by fm-sys** [comment]
How do regular browsers on android behave? Possibly it's a general problem on android independent of the app...

**Comment by fm-sys** [comment]
Closing due to lack of feedback
