### ISSUE TITLE
make it available offline

### ISSUE THREAD

**Issue by Joeeeeb5** [fm-sys/snapdrop-android#333]
### Describe the feature

i need to have internet access from a router to share a file. it would be better if i could turn on hotspot, someone connects to it and i share files.

### Describe alternatives you've considered

used nearby share but it doesnt work well. takes ages to find a device and slow transfer speeds.

**Comment by fm-sys** [comment]
Not possible, unfortunately, as Snapdrop/PairDrop is intended to also work just with a browser.
