### ISSUE TITLE
snapdrop-android translations overwrite translations provided by pairdrop.net 

### ISSUE THREAD

**Issue by schlagmichdoch** [fm-sys/snapdrop-android#334]
### App version

latest

### Android version

newer

### Describe the bug

If you take a look here:
<image src="https://user-images.githubusercontent.com/119143925/276644618-02c9bb5b-2091-406c-8ef8-007b8539bc52.jpg" width="300px">

you can see, that the complete Spanish translation is overwritten by the apps translations.

Would it be possible to prevent translations for PairDrop for languages that are supported by PairDrop itself (see [here](https://pairdrop.net/scripts/localization.js))?

### Steps to reproduce the bug

1. switch phone language to Spanish
2. Go to pairdrop.net via this app

**Comment by fm-sys** [comment]
This is a good suggestion!

PRs are welcome, don't have time to work on this myself in the near future. IMHO it would even be fine to disable website translation at all when pairdrop is detected
