### ISSUE TITLE
Did the whole pairdrop repo just vanished?

### ISSUE THREAD

**Issue by terrytw** [fm-sys/snapdrop-android#356]
### App version

Lastest

### Android version

12

### Describe the bug

I don't know whether this is the best place to put up this issue, honestly I don't know a better place, at least it is connected to this project

### Steps to reproduce the bug

Well go to https://github.com/schlagmichdoch/PairDrop

**Comment by fm-sys** [comment]
Good question. I have absolutely no idea what happened... The whole user account of the pairdrop maintainer doesn't exist anymore.

As I wasn't informed by him, I don't think that was intentional.🤔

**Comment by terrytw** [comment]
> The whole user account of the pairdrop maintainer doesn't exist anymore.

Yeah I noticed that as well. Maybe he got hacked...I DMed him on reddit too but no response so far.

**Comment by cethemaco** [comment]
> > The whole user account of the pairdrop maintainer doesn't exist anymore.
> 
> Yeah I noticed that as well. Maybe he got hacked...I DMed him on reddit too but no response so far.

Where did you message him? Going to https://www.reddit.com/user/schlagmichdoch reveals that the account was deactivated

**Comment by stil-blue** [comment]
Hey @terrytw ,

@schlagmichdoch here. I'm using my second account as GitHub has somehow shadow hidden my main account from the public including all my repositories, alongside any PR, issue or comment I ever created on other repos.
They also deleted some issues and many comments I made completely using an automation called [hubot](https://hubot.github.com/).

Logged into my main account, everything looks normal. I did not get any notification by GitHub about this and I only recognized that something was off, as all of the image URLs that link to assets in one of my repositories return a 404 and are not visible to anyone (including me). First, I thought this was some kind of disturbance with GitHub itself but apparently everything was up and running normally. Only after finding a blog post on medium.com which described the exact same situation I knew what was going on.
If you want to read into it, it's a good blog post by a guy to whom this happened 4 years ago who has since moved over to GitLab:
https://medium.com/@catamphetamine/how-github-blocked-me-and-all-my-libraries-c32c61f061d3

GitHub has notified me on Saturday via an E-Mail stated 'Password reset and token revocation notification due to suspicious activity'. This is normally sent to users if they were hacked and their account is used for distribution of malware. Although I'm quite certain that I was not hacked, I changed my password and activated 2FA since.

The whole situation is super weird and frustrating as I was about to release a major update to PairDrop. I'm also completely in any communication which is eery.

I have filed a complained via a support ticket to reinstate my account yesterday.

The blog post says GitHub responded after a week, others estimate it takes around 2 weeks until they respond. Until then, I will use this account for communicating my current situation, so I cannot do anything but be patient..

My reddit handle is [_schlagmichhalt_](https://www.reddit.com/user/schlagmichhalt/) and my mail address is sonnig-02.hieven@icloud.com if you want to contact me directly.

Take care!

**Comment by terrytw** [comment]
@stil-blue Hi I am glad that you are all right! 

I got your reddit reply as well, I am just going to answer it here since I don't think it involves anything particularly private:
> How did you recognize it being vanished?
I was just going to check on the commit history since I am quite interested in the upcoming new minor release you mentioned the other day. So I went to https://github.com/schlagmichdoch/PairDrop/ and I got this:
![image](https://github.com/fm-sys/snapdrop-android/assets/24227628/a15ee104-6fb7-4d0a-9e02-2e0f6e622305)

That is it, sorry the story is just this short and I cannot provide more information. Then I tried https://github.com/schlagmichdoch it is still 404. Then I just posted this issue, because I thought maybe the maintainer here knows about what happened.

**Comment by fm-sys** [comment]
Hi @stil-blue,

Glad to hear that you are fine! Definitely wouldn't have expected Github to behave that impulsive, but let's just hope the best. And don't let it get you down, we all appreciate your great work!

Cheer up!

**Comment by stil-blue** [comment]
Thanks for the kind words! 

They will have their reasons for restricting the account. I'm just really annoyed that I did not get notified at all about the procedure. As the blog post states it would be understandable to put the account into read-only but shadow hiding is not transparent and really restrictive.

I guess it's gonna be alright. I will keep you updated!

**Comment by KaKi87** [comment]
@stil-blue In the meantime, I'd like to suggest pointing the GitHub links from pairdrop.net/#about to this issue or any other place explaining the situation.

Thanks

**Comment by stil-blue** [comment]
@KaKi87 That is a good idea.

I will point the GitHub link to this issue and the FAQ button on directly to a forked FAQ

You can find code and docs of the latest fork here:

### README / code
https://github.com/babstar99/PairDrop

### Docs
https://github.com/babstar99/PairDrop/blob/master/docs/host-your-own.md

### FAQ
https://github.com/babstar99/PairDrop/blob/master/docs/faq.md

**Comment by xundeenergie** [comment]
> Hey @terrytw ,
> 
> @schlagmichdoch here. I'm using my second account as GitHub has somehow shadow hidden my main account from the public including all my repositories, alongside any PR, issue or comment I ever created on other repos. They also deleted some issues and many comments I made completely using an automation called [hubot](https://hubot.github.com/).
> 
> Logged into my main account, everything looks normal. I did not get any notification by GitHub about this and I only recognized that something was off, as all of the image URLs that link to assets in one of my repositories return a 404 and are not visible to anyone (including me). First, I thought this was some kind of disturbance with GitHub itself but apparently everything was up and running normally. Only after finding a blog post on medium.com which described the exact same situation I knew what was going on. If you want to read into it, it's a good blog post by a guy to whom this happened 4 years ago who has since moved over to GitLab: https://medium.com/@catamphetamine/how-github-blocked-me-and-all-my-libraries-c32c61f061d3
> 
> Depending on the outcome of this ordeal, I really need to think about moving ship too.
> 
> GitHub has notified me on Saturday via an E-Mail stated 'Password reset and token revocation notification due to suspicious activity'. This is normally sent to users if they were hacked and their account is used for distribution of malware. Although I'm quite certain that I was not hacked, I changed my password and activated 2FA since.
> 
> The whole situation is super weird and frustrating as I was about to release a major update to PairDrop. I'm also completely invisible in any communication which is very eery.
> 
> I have filed a complained via a support ticket to reinstate my account yesterday.
> 
> The blog post says GitHub responded after a week, others estimate it takes around 2 weeks until they respond. Until then, I will use this account for communicating my current situation, so I cannot do anything but be patient..
> 
> My reddit handle is [_schlagmichhalt_](https://www.reddit.com/user/schlagmichhalt/) and my mail address is [sonnig-02.hieven@icloud.com](mailto:sonnig-02.hieven@icloud.com) if you want to contact me directly.
> 
> Take care!

My dear... 

So... never trust big companies owned by billionairs... 

Host your own forgejo-instance and you are on again with a great git.
Host your own gitlab-instance and you are on again with another great git.
Host your repo on codeberg.org (which uses forgejo) and your are part of a big community NOT owned by a fucking billionair... 

The fine thing on forgejo is, it will sometimes federate... so you can have your own git-server and create federated issues, comments and so on... the next step git. :)

And... get a fediverse-account... reddit is the next bad thing, owned by billionairs. 
Lemmy https://github.com/LemmyNet/lemmy is a very good alternative to reddit... selfhostable, federating (with the whole fediverse)...

**Comment by archef2000** [comment]
The account is still not back. @stil-blue anything new?

**Comment by stil-blue** [comment]
Nope. It's outrageous but 20 days after creating the ticket, support has yet to answer it. I'll definitely move ship next week.

The only thing that I have found out is that my account is flagged as spam which is different to what I thought (username/reponame seems ok). I guess it's just a shitty spambot on their end which falsely flagged me.

**Comment by KaKi87** [comment]
+1 for [Codeberg](https://codeberg.org/) or self-hosting Forgejo rather than GitLab.

**Comment by kaindlnetwork** [comment]
@stil-blue :) You can still count on me for financial and compute ressource capacity. If you want i could even start an own gitlab instance (i currently know only gitlab and github to administer). Waiting for orders ;) 
![Uploading image.png…]()

**Comment by KaKi87** [comment]
> i currently know only gitlab

If you can instanciate GitLab then you can for sure instanciate Forgejo, which is dead simple in comparison (it's a single executable and a single config file).

**Comment by andreasf** [comment]
@stil-blue if you are in the EU, you can send Github a GDPR Data Subject Request to ask them if any automated decision making was made, how they prevent errors in the process and how you can challenge the decision.

https://noyb.eu/en/exercise-your-rights-article-22-be-protected-automated-decision-making

**Comment by SimonSchick** [comment]
@stil-blue

Can you please clarify whether you had 2fa enabled prior to this?

**Comment by sean-7777** [comment]
@stil-blue Hey, any updates on this? Really unfortunate situation you're in, hope GitHub fixes this soon.

**Comment by terrytw** [comment]
It has only been 2 days since he last replied, so it is unlikely things
have changed. I propose that we don't ask for update so frequently. If the
GitHub account and repo comes back, we can all see it, right? If the
maintainer decides to move on to Gitlab or wherever, I'm sure he will let
us know. For now, let's be patient.

**Comment by schlagmichdoch** [comment]
I’m back!

Just a quick update that everything seems to be back to normal.

Tonight suddenly my cronjob succeeded again: https://75dgf6sc.status.cron-job.org/

Once again I have not gotten any notification from GitHub and my tickets are still unanswered.

I will evaluate the situation in the next hours and check if everything is as expected. I will probably still move the repo after the next release and turn the repo here into a mirror. For now, I’m just happy that all the information in the issues, PR and comments is not lost.

Cheers
Dominik

**Comment by KaKi87** [comment]
> I’m just happy that all the information in the issues, PR and comments is not lost.

By the way, Forgejo can import those (I don't know about GitLab but I don't think so).

**Comment by schlagmichdoch** [comment]
> > I’m just happy that all the information in the issues, PR and comments is not lost.
> 
> By the way, Forgejo can import those (I don't know about GitLab but I don't think so).

I have read that and it’s great! All of these imports use GitHub plugins though and these are disabled for flagged accounts so that wasn‘t an option until now.

**Comment by KaKi87** [comment]
> these are disabled for flagged accounts so that wasn‘t an option until now.

Of course, that's why I only mentioned that now.

**Comment by terrytw** [comment]
> I’m just happy that all the information in the issues, PR and comments is not lost.
Great news!

> Once again I have not gotten any notification from GitHub and my tickets are still unanswered.
I did some napkin math and it seems to be around 30 days after the incident, maybe there is some kind of automatic system which they rely on probably too much. 

@schlagmichdoch I'm considering closing this issue, do you want to continue the discussion here or publish some kind of announcement on the front page of your repo?

**Comment by schlagmichdoch** [comment]
> these are disabled for flagged accounts so that wasn‘t an option until now.

I was wrong here. I have used the migration tool of Codeberg and they use an access token and the GitHub API which would have worked while being flagged.

While GitLab uses a plugin feature which is blocked when flagged, Codeberg uses the GitHub API which makes migrating PR and issues possible.
 
> I did some napkin math and it seems to be around 30 days after the incident, maybe there is some kind of automatic system which they rely on probably too much.

I have had that thought too. It's 32 days which is a weird automatic limit but possible of course. Sadly, they have only unflagged my account but have not restored deleted issues and comments. As soon as everything is restored, I will migrate the repo to Codeberg. Thanks to everyone for the recommendation!

> @schlagmichdoch I'm considering closing this issue, do you want to continue the discussion here or publish some kind of announcement on the front page of your repo?

Sure, go ahead! I have added a pinned issue to the main repo here: https://github.com/schlagmichdoch/PairDrop/issues/284. Anyone interested should subscribe to the issue as I will post anything new over there.

Also, I have reverted the changes to pairdrop.net to point to the main repository again.

**Comment by xundeenergie** [comment]
Hi!

> I have had that thought too. It's 32 days which is a weird automatic limit but possible of course. Sadly, they have only unflagged my account but have not restored deleted issues and comments. As soon as everything is restored, I will migrate the repo to Codeberg. Thanks to everyone for the recommendation!

great News!

Thank you for this step.

See you there!

**Comment by dpteams** [comment]
I don't have real-time [information](https://skyviewpaintings.com/burnaby/wood-repair/) on specific GitHub repositories or issues. If you're referring to the disappearance of a repository or an issue (#356) on GitHub, here are a few steps you can take to investigate:

Check the Repository [URL](https://honestus.ca/hamilton/flooring-contractor/): Double-check the URL of the repository to ensure you are accessing the correct repository.

Verify Access: Make sure you have the necessary permissions to view the repository. Sometimes repositories may be private or restricted.

Search for Issues: If you're [looking for](https://hvacaplus.ca/brampton/air-conditioner-repair/) a specific issue (#356), you can search for it within the repository's issues tab or use GitHub's search functionality.

Repository Visibility: Ensure the repository has not been made private or deleted by the owner. GitHub typically shows a message if a repository has been deleted or made private.

Community or Support: If you're part of a community related to the repository or project, [checking](https://golfclubs129.com/golf-clubs/are-pxg-clubs-good/) with other members or the maintainers may provide insights into any changes or issues.

If the repository or issue indeed seems to be missing and you cannot find any explanation, reaching out to GitHub support or the repository owner (if possible) might be the next step to understand what happened.
