### ISSUE TITLE
Transfer files to PC individually instead of zip

### ISSUE THREAD

**Issue by anthonyg2003** [fm-sys/snapdrop-android#359]
### Describe the feature

When transferring multiple files from android phone to PC (pairdrop.net via Chrome browser), the default behavior seems to be to bundle the files into a .zip file. This results in having to take an extra step to unzip files. A bundled zip file is great for large # of files, but annoying when it's two or three photos. Transferring files from PC > Android doesn't do this.

Possible that this is a settings options somewhere, but I couldn't find it in the snapdrop app or on the pairdrop.net portal.

I did see on pairdrop github (https://github.com/babstar99/PairDrop/tree/master#improved-ui-for-sendingreceiving-files) that downloading multiple files as .zip is a feature, but seems not to be a selectable feature. The issue forum for pairdrop appears to be turned off so I could not post this there, and so hoping something can be done on snapdrop app side to alter this behavior.

### Describe alternatives you've considered

Perhaps have option, after selecting multiple files on android device, for snapdrop to send multiple files as individual packets so that pairdrop doesn't bundle them into a .zip. 

Understandable if the recipient would have to accept each file individually. Still easier than sending files individually or having to unzip a bundle file.

### Additional context

Android Device:
- Android 14
- Snapdrop & Pairdrop for Android v 2.2.4 (via F-Droid)

PC:
- Chrome 122.0.6261.128
- pairdrop.net (showing v1.10.7)

**Comment by fm-sys** [comment]
This issue has clearly nothing to do with the app, thus I would like to recommend opening an issue in the pairdrop repository instead. Unfortunately, [the pairdrop repository is currently not available...](#356)

**Comment by anthonyg2003** [comment]
@fm-sys : Yes, understood that the bundling is done by pairdrop, but wouldn't the suggestion of a user-selectable option for snapdrop to send multiple files as individual share requests be a possible feature request for the snapdrop app?

**Comment by fm-sys** [comment]
Totally agree. However, as far as I know the files are already sent as individual files. It's just the web frontend which zips the files for download. This is done because some browsers don't allow multiple file downloads at once. Not sure if it's possible to work around that problem. 

Am I right, @stil-blue (pairdrop maintainer)?

**Comment by schlagmichdoch** [comment]
> It's just the web frontend which zips the files for download. This is done because some browsers don't allow multiple file downloads at once.

This is true. As the repository is back, let's move the discussion over there.

As this is also related to the issue here discussing the download dialog: https://github.com/schlagmichdoch/PairDrop/issues/40 I would suggest adding your request over there @anthonyg2003 and closing this issue.

**Comment by fm-sys** [comment]
Thanks for the insights here and in https://github.com/schlagmichdoch/PairDrop/issues/40. Let's close in favor of that issue.
