### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by ln-12** [fm-sys/snapdrop-android#38]
I really love to open snapdrop via the share menu with a file pre-selected. Now I would like to build the same solution for iOS. It's no problem to open the app from the share menu but I don't know how I would preselect a file so that it is directly sent to the peer when clicked. I only found [this line](https://github.com/fm-sys/snapdrop-android/blob/master/app/src/main/java/com/fmsys/snapdrop/JavaScriptInterface.java#L198) when a string is shared, but how do you handle files? I can't find the place where you submit the file url to snapdrop...

**Comment by fm-sys** [comment]
Hi @ln-12! Nice to hear that you like my app 😁

In android there is a method called `onShowFileChooser` which provides an upload callback. However I have no idea how it can be done at iOS... 🤷‍♂️

https://github.com/fm-sys/snapdrop-android/blob/dbb57f94c459e0e0d42581db2388aeca8c51d448/app/src/main/java/com/fmsys/snapdrop/MainActivity.java#L277-L295

**Comment by ln-12** [comment]
Ah, I see. so you don't inject the files via JavaScript into the website but simply return the Uri via the callback. That helped a lot, thank you very much!

**Comment by fm-sys** [comment]
No problem! Nice to hear, that I was able to help you...
