### ISSUE TITLE
Help to translate Snapdrop for Android into your language

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#43]
Recently, **Snapdrop for Android** has been added to [Crowdin](https://crowdin.com/project/snapdrop-android), which makes it much easier to participate in translation.

If you want to help, but your favorite language is not yet available, just add a small comment in this issue and write in which language you want to translate Snapdrop, and I will activate the language for you as soon as possible!

<p align="center">
  <a href="https://crowdin.com/project/snapdrop-android" rel="nofollow">
    <img src="https://badges.crowdin.net/badge/dark/crowdin-on-light.png" srcset="https://badges.crowdin.net/badge/dark/crowdin-on-light.png 1x,https://badges.crowdin.net/badge/crowdin-on-light@2x.png 2x"  alt="Crowdin | Agile localization for tech companies" />
  </a>
</p>

**Comment by Krrishdhaneja** [comment]
Hey, I can help you in translating the app to Hindi 😃

**Comment by Krrishdhaneja** [comment]
Btw which files i'll have to edit?

**Comment by fm-sys** [comment]
I just now activated Hindi at crowdin. It's quite intuitive, so just try it out ;-)

See https://crowdin.com/translate/snapdrop-android/all/en-hi

**Comment by Krrishdhaneja** [comment]
So i'll have to translate strings.xml??

**Comment by fm-sys** [comment]
Exactly, `strings.xml` is for inside the app. Everything else is definitely optional and might be used for [playstore description](https://play.google.com/store/apps/details?id=com.fmsys.snapdrop), etc...

**Comment by Krrishdhaneja** [comment]
But wait there is another snapdrop on play store too with yours !
->
![Screenshot_20210318-142114_Google Play Store.jpg](https://user-images.githubusercontent.com/65185487/111598439-3cb27e00-87f5-11eb-8ba4-4db241a57d6c.jpg)

**Comment by fm-sys** [comment]
Yep, since a few weeks. I've also tried the app, but it doesn't do well. Changed filenames, no settings for device name, ... But yes, I was aware of it. Even though my app has been around for a few months, I hadn't uploaded it to Google Play so he has unfortunately uploaded it earlier. But you can advertise my version in your circle of acquaintances 😁

**Comment by Krrishdhaneja** [comment]
N.P.

**Comment by Sciroccogti** [comment]
I can try to help with translation to Chinese 😄

**Comment by fm-sys** [comment]
I activated Chinese Simplified at crowdin just now. Hope that was right. Looking forward 😃

**Comment by Sciroccogti** [comment]
During the translation, I noticed a typo maybe:
https://github.com/fm-sys/snapdrop-android/blob/7899a87affe1bc6679998c9ae2e69c89ff6bcd47/app/src/main/res/values/strings.xml#L13
should `Tab` be `Tap`?

**Comment by fm-sys** [comment]
> 
> 
> During the translation, I noticed a typo maybe:
> 
> https://github.com/fm-sys/snapdrop-android/blob/7899a87affe1bc6679998c9ae2e69c89ff6bcd47/app/src/main/res/values/strings.xml#L13
> 
> should `Tab` be `Tap`?

Yep, you're totally right. Thanks for the hint! :)

**Comment by Sciroccogti** [comment]
I wonder how can I switch to another language? My android system is in zh-cn, and I downloaded the apk from github, but it continues to be English version and there doesn't seem to be an entrance for language switching.

**Comment by fm-sys** [comment]
I accidentally forgot to download the crowdin updates before compiling the APK. I have now recompiled the APK file. Could you download and install it again? Maybe that will solve the problem...

**Comment by fm-sys** [comment]
And BTW, the website will currently always occur in English. Only settings, etc. are localized. But we can try to change this in new versions. Contributions welcome ;)

**Comment by Sciroccogti** [comment]
> I accidentally forgot to download the crowdin updates before compiling the APK. I have now recompiled the APK file. Could you download and install it again? Maybe that will solve the problem...

Yep it's all right now! Great work!

**Comment by TheLimifiedLime** [comment]
Hey. I just wanna say that I went and did a bunch of the spanish translations. Hope this helps!

**Comment by Kazvko** [comment]
I would love to translate it to brazillian portuguese pt-br

**Comment by fm-sys** [comment]
> 
> 
> I would love to translate it to brazillian portuguese pt-br

Added to [crowdin](https://crowdin.com/project/snapdrop-android). Looking forward to your contribution :)

**Comment by Kazvko** [comment]
> > I would love to translate it to brazillian portuguese pt-br
> 
> Added to [crowdin](https://crowdin.com/project/snapdrop-android). Looking forward to your contribution :)

It was easier than i thought, done!

**Comment by junyou1998** [comment]
I  want to help with translation to "Chinese Traditional" ,please activate the language🙏

**Comment by fm-sys** [comment]
> I want to help with translation to "Chinese Traditional" ,please activate the language🙏

Done. Looking forward ;-)

**Comment by Kornphan** [comment]
Amen. May I have it in Thai language?

**Comment by fm-sys** [comment]
> May I have it in Thai language?

Thanks for your offer. I've just activated "Thai" on Crowdin. You can start [here...](https://crowdin.com/translate/snapdrop-android/all/en-th) Looking forward to your contribution :)

**Comment by Kornphan** [comment]
Suko Hanaka

**Comment by ducanhmai521** [comment]
what about vietnamese ;)

**Comment by fm-sys** [comment]
> what about vietnamese ;)

Enabled... 👍

https://crowdin.com/translate/snapdrop-android/all/en-vi

**Comment by ducanhmai521** [comment]
> https://crowdin.com/translate/snapdrop-android/all/en-vi
Done! Can't wait to see that in the next update

**Comment by KimWash** [comment]
How about korean?

**Comment by fm-sys** [comment]
> How about korean?

Here we go...

https://crowdin.com/translate/snapdrop-android/22/en-ko

**Comment by zenolabs** [comment]
Please add italian language.

**Comment by fm-sys** [comment]
> Please add italian language.

Added...

https://crowdin.com/translate/snapdrop-android/22/en-it

**Comment by syarifulanwar** [comment]
Please add Bahasa Indonesia. Thanks!

**Comment by fm-sys** [comment]
> Bahasa Indonesia

Should be enabled now...

**Comment by fm-sys** [comment]
Due to recent **vandalism** in the **Crowdin Project** I will no longer be able to use all translations without an **additional review**. 

However, I'm glad that there are so many who have contributed to this app in a great way in their free time... Big thank you, guys!

I will continue to use crowdin, however I need some of you who volunteer to help as a proofreader. **Who is interested?** 

If so, please contact me via a Crowdin private message, or add a short comment here... 

Sorry for the additional work, but I'm forced to go this step to maintain our current translation quality due to some stupid people... :-/

**Comment by fm-sys** [comment]
Situation got calm again until now...

Maybe we can continue to use translations via "upvote" principle and without explicit peer2peer review. Anyway, I think we have enough languages for now containing most of the larger languages...

If an important language should be still missing, please open a new issue. Thanks for all your contributions!

**Comment by Aqua22** [comment]
Hi! Could you add Hungarian, please? Thanks!

**Comment by fm-sys** [comment]
> Hi! Could you add Hungarian, please? Thanks!

Hi @Aqua22, I've just checked the playstore statistics:
Currently, 170 out of 72.000 users are using Hungarian as their phone language. That's approximately 0.2% of our user base.

I'm a bit undecided whether we should really maintain languages with a user base of <1%. For me, it's always difficult to review languages which I'm not familiar with... Especially as most of the main UI currently isn't localized anyway (#69)

**Comment by Aqua22** [comment]
Sure! That's fine with me maybe in the future when the main UI is localized then there could be a Hungarian translation by me or some other user.

**Comment by Jan-Bujnosek** [comment]
Hello, I would love to translate it to Czech language. Can you please add it to Crowdin? Thank you!

**Comment by fm-sys** [comment]
@Jan-Bujnosek I've just enabled Czech on crowdin. Looking forward to your translations :)

**Comment by fm-sys** [comment]
Hi @Aqua22, are you still interested in a Hungarian translation? 

We have started to localize the main UI meanwhile and to cross-reading problem is somewhat solved meanwhile... The possibility to review all translations was and is important for us, as we want to provide a good user experience and unfortunately we had some rare cases of vandalism in the past. Therefore we have implemented a bot, which generates reverse-translated English strings, so we can review new languages easier which we don't understand ourselves.

**Comment by Medo172** [comment]
Hi, I would like to try and translate Snapdrop into the Slovenian language.

**Comment by fm-sys** [comment]
> Hi, I would like to try and translate Snapdrop into the Slovenian language.

@Medo172: enabled :)

**Comment by ItsNoxL** [comment]
Can there be a Slovak translation?

**Comment by Aqua22** [comment]
> Hi @Aqua22, are you still interested in a Hungarian translation? 
> 
> We have started to localize the main UI meanwhile and to cross-reading problem is somewhat solved meanwhile... The possibility to review all translations was and is important for us, as we want to provide a good user experience and unfortunately we had some rare cases of vandalism in the past. Therefore we have implemented a bot, which generates reverse-translated English strings, so we can review new languages easier which we don't understand ourselves. 

Hi! Yes, I am still intrested.

**Comment by fm-sys** [comment]
I've just enabled Slovak. Hungarian was already enabled some weeks ago...

**Comment by Alexandru51** [comment]
Hi, can be there a romanian translation?

**Comment by fm-sys** [comment]
@Alexandru51 I've just enabled the Romanian language at crowdin... So you can go ahead :)

**Comment by Alexandru51** [comment]
> @Alexandru51 I've just enabled the Romanian language at crowdin... So you can go ahead :)

I did the translation, and thanks for enabling :)

**Comment by kobyrevah** [comment]
Please add Hebrew language!!!

**Comment by fm-sys** [comment]
> Please add Hebrew language!!!

enabled :)

**Comment by kobyrevah** [comment]
@fm-sys on it. Thanks.

**Comment by alizhumagaliev** [comment]
Please add Karakalpak language.

You can add it as a custom language on crowdin.

Here is the information about the language:

Language name: Karakalpak
The dialect of: Not chosen
Crowdin code: kaa
Three letters code:kaa
Locale code: kaa
Text direction: left to right
Plural form: one, other

Thanks!

**Comment by alizhumagaliev** [comment]
Please add Karakalpak language!!!

**Comment by sergd88** [comment]
Hi, I would like to try and translate Snapdrop into the Ukrainian language.

**Comment by sergd88** [comment]
> Recently, **Snapdrop for Android** has been added to [Crowdin](https://crowdin.com/project/snapdrop-android), which makes it much easier to participate in translation.
> 
> If you want to help, but your favorite language is not yet available, just add a small comment in this issue and write in which language you want to translate Snapdrop, and I will activate the language for you as soon as possible!
> 
> [ ![Crowdin | Agile localization for tech companies](https://camo.githubusercontent.com/862f0e5d33949d0dacc6d9f7749efbdc7860bec2ca7f1bd3f47387cecaa21f42/68747470733a2f2f6261646765732e63726f7764696e2e6e65742f62616467652f6461726b2f63726f7764696e2d6f6e2d6c696768742e706e67) ](https://crowdin.com/project/snapdrop-android)

Hi, I would like to try and translate Snapdrop into the Ukrainian language.

**Comment by fm-sys** [comment]
> Hi, I would like to try and translate Snapdrop into the Ukrainian language.

Ukrainian language is now available... Thanks for your support!

**Comment by sergd88** [comment]
> > Hi, I would like to try and translate Snapdrop into the Ukrainian language.
> 
> Ukrainian language is now available... Thanks for your support!

Just great, already translated 🙃
