### ISSUE TITLE
custom server

### ISSUE THREAD

**Issue by farfromrefug** [fm-sys/snapdrop-android#44]
could you add support for custom server URL ? I use my own snapdrop with docker on my local network.
thanks

**Comment by fm-sys** [comment]
Indeed, I'm already using kind of a custom server cause I had to make some changes to the front-end UI but the requests are still directed to the main server https://snapdrop.net. 

If you're request is just about the backend, this would be quite easy to implement...

**Comment by farfromrefug** [comment]
@fm-sys yes just the backend url as an option. Would be pretty awesome!
THanks

**Comment by ueen** [comment]
this might be even easier now that all app related js is injected right inside the app, so if the the backend is matching the implementation of snapdrop.net it could be an easy url swap
