### ISSUE TITLE
Notification don't gets shown on older API's

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#5]

**Comment by AtjonTV** [comment]
Here is a little bit of Kotlin source code from my app (https://billstar.app).

I confirmed that code to work on API 19 up to 30. You will either have to add Kotlin to your project, or translate it to Java.

The createNotificationChannel has to be called during the creation of your main activity and wrapped in a Version check, the sendNotification can then be called from anywhere.

```kotlin
object Notify {
    private val channel = "UPDATE"
    private val channelDescription = "Get all updates to events"
    private var notifyId = 1

    fun sendNotification(title: String, text: String) {
        val mBuilder =
            NotificationCompat.Builder(context, channel)
                .setContentTitle(title)
                .setContentText(text)
                .setPriority(NotificationCompat.PRIORITY_LOW)
                .setAutoCancel(false)

        val notificationManager = NotificationManagerCompat.from(context)
        notificationManager.notify(notifyId++, mBuilder.build())

    }
    
    @RequiresApi(Build.VERSION_CODES.O)
    fun createNotificationChannel() {
        // Create a new Notification Channel (Android 8 [API 26] and later)
        val importance = NotificationManager.IMPORTANCE_DEFAULT
        val channel = NotificationChannel(channel, channel, importance).apply {
            description = channelDescription
        }
        // Register the channel with the system
        val notificationManager: NotificationManager =
            getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        notificationManager.createNotificationChannel(channel)
    }
}
```

As you dont need a channel on pre O android, it should "just work". My app will drop support for API pre 21, but 21 is your target too anyways.

As my app is closed source, I had to strip some stuff our, if that code above does not work I am happy to help fix what I messed up during stripping.

**Comment by fm-sys** [comment]
@AtjonTV thanks for providing this information! I will take a deeper look into it in the next few days, and may come back to you if I don't get it working...
