### ISSUE TITLE
Copy text message to clipboard does not work

### ISSUE THREAD

**Issue by FrankSchuehlein** [fm-sys/snapdrop-android#57]
When sending a text message from another device to snapdrop app on Android  a pop-up appears showing text (ok) but text cannot be copied to clipboard by pressing button. Using snapdrop browser version works correctly

Samsung S7, Android 8

**Comment by fm-sys** [comment]
Yep, looks like something got broken. I've fixed the bug and just released a new version. You can find it at [GitHub](https://github.com/fm-sys/snapdrop-android/releases/tag/v1.5.1) or [Google Play](https://play.google.com/store/apps/details?id=com.fmsys.snapdrop)... Hope it works!
