### ISSUE TITLE
Usage with ethernet or wifi-hotspot connection not possible on Android

### ISSUE THREAD

**Issue by FrankSchuehlein** [fm-sys/snapdrop-android#58]
If device is connected to LAN via ethernet (e.g. Android TV) or device has created a wifi hotspot then snapdrop app simply reports that you have to be connected with a wifi network to use it. I consider this as a bug as in both cases device is inside a LAN. Browser version of snapdrop correctly waits/scans for devices

Orbsmart S85 Android 9
Samsung S7, Android 8

**Comment by fm-sys** [comment]
Related to #46 and #48. It's still on my todo list, hopefully I will find time for it very soon... Sorry for the inconvenience!

**Comment by fm-sys** [comment]
See https://github.com/fm-sys/snapdrop-android/issues/48#issuecomment-817358647. There I posted a screenshot, how the first solution will look like. Feel free to suggest better ideas...
