### ISSUE TITLE
Android Snapdrop 100MB File Limit

### ISSUE THREAD

**Issue by FarukOzderim** [fm-sys/snapdrop-android#68]
**Describe the bug**

**To Reproduce**
1. Go to 'Snapdrop ubuntu - snapdrop android'
2. Share a file over 100MB to android. 
3. Download the file when sending is over.

**Expected behavior**
File is downloaded normally.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20]
 - Browser [Firefox]
 - Version [20]
 
**Smartphone (please complete the following information):**
 - Device: [Oppo Realme 7]
 - OS: [10]
 - Browser [Snapdrop App]
 - Version [v0.2]

**Additional context**
Files under 100MB are downloading perfectly.
I have tried with 2 different files over 100MB and I can not download them.

**Comment by Krrishdhaneja** [comment]
I too tried to send a file above 100 mb to see if I have this issue too, and yes I do, I tried to share an apk above 100 mb and it wasn't successful, when I clicked on save, I wasn't able to save it.

**Comment by ueen** [comment]
will be fixed soon https://github.com/fm-sys/snapdrop-android/pull/76

**Comment by fm-sys** [comment]
Fixed with #76
