### ISSUE TITLE
A section in app for logs

### ISSUE THREAD

**Issue by Krrishdhaneja** [fm-sys/snapdrop-android#71]
**Is your feature request related to a problem? Please describe.**
Not exactly, actually I thought that there must be a logs section in the app(maybe a section in settings)as it may help the collaborators to reproduce the issues easily and fastly

**Describe the solution you'd like**
I think a section devoted to logs should be in the app, as it will help to analyse the problem easily.

**Comment by fm-sys** [comment]
Fixed by 4880e96b8b2ec5cb038fa49a5a2f3fec94b64c23
