### ISSUE TITLE
App should show better error message when Snapdrop Server is not accessible 

### ISSUE THREAD

**Issue by Fabioni** [fm-sys/snapdrop-android#72]
**Describe the bug**
When the Website Snapdrop.net is not accessible the App just shows the typically browser error.

Currently it looks like this:
![](https://user-images.githubusercontent.com/45362676/114904499-37f2e100-9e18-11eb-8126-757c993ca572.png)

**To Reproduce**
1. Snapdrop.net is down 
2. open the app and wait for some seconds

**Expected behavior**
An app-looking error message.

**Comment by fm-sys** [comment]
Note: You are not using the "Snapdrop for Android" app which is hosted in this repository but a different third party application.

This app shows following screen (but I guess this is not much better):
![Screenshot_20210415_203503_com fmsys snapdrop_copy_270x585](https://user-images.githubusercontent.com/64581222/114920912-3f22ea80-9e2a-11eb-905d-34646e9617a2.jpg)

**Comment by Fabioni** [comment]
I'm using the Snapdrop | shareIt (early access) App from the Google Play Store. Is this not the right one?

15.04.2021 20:37:10 Florian ***@***.***>:

**Comment by fm-sys** [comment]
This repo id about https://play.google.com/store/apps/details?id=com.fmsys.snapdrop. My app started a few weeks later. Therefore, unfortunately it is not at the top in the ranking and has also significantly less downloads. This app provides additional functionalities like changing the device name, etc... (Of course only if the server works ;-) )

**Comment by Sciroccogti** [comment]
Well, I also want to report a similar situation: This app won't give a way to settings if the server is done as shown below.

![Screenshot_2021-05-07-17-19-11-535_com fmsys snap](https://user-images.githubusercontent.com/32357397/117428146-5e5bf600-af58-11eb-8cfe-16fe34386187.jpg)

**Comment by fm-sys** [comment]
As a workaround, you can disable your wifi connection. Then it will show a screen with the settings gear at the top. But you're right, that this definitely can be optimized...

**Comment by fm-sys** [comment]
AFAIK this should be solved meanwhile...
