### ISSUE TITLE
I fear we messed up

### ISSUE THREAD

**Issue by ueen** [fm-sys/snapdrop-android#73]
After the recent update with the js injection right into the original snapdrop.net i often encounter the app in a state where it is just displaying the page without the js injections, which of course messes up functionality like copying.
I suspect that it may have something to do with `loadAgain` it seems somewhat hacky to me, could you explain why you implemented it and if it could be removed?

This often appears when started new (`onCreate`) and i'm sometimes able to fix it by moving the app to the background and then to the foreground again (`onResume`).

**Comment by ueen** [comment]
https://github.com/fm-sys/snapdrop-android/pull/74

**Comment by fm-sys** [comment]
> I suspect that it may have something to do with loadAgain it seems somewhat hacky to me, could you explain why you implemented it and if it could be removed?

For sure this is a very hacky workaround. Actually I tried to remove that workaround before releasing the new version but somehow the app shows itself as peer which is gone after a website reload. But I can try to debug into it again...

**Comment by ueen** [comment]
The PR fixes the injection isssue.
Yea the showing itself seem to be due to this code
`if (onlinePastThreeMin()) {
            WebStorage.getInstance().deleteAllData();

            cookieManager.setCookie("https://snapdrop.net/",
                    "peerid=" + UUID.randomUUID().toString() + ";" +
                            "path=/server;" +
                            "max-age=86400;"
            );
        }`
if removed it doesnt show itself anymore...
Is this code requiered for anything else?

**Comment by fm-sys** [comment]
> Is this code requiered for anything else?

It was required when using my github fork, but probably not when using the original website. Thanks for finding the fix 😃👍

I will try your PR and report back...

**Comment by ueen** [comment]
I have to say it seems no different if this code is remved or not and i also encountered the app showing itself sometimes with `loadAgain` and the `cookies` so i think we can remove that code, then at least the js injection works, but the showing itself issue remains...let me see if i find something int the snapdrop repo

**Comment by ueen** [comment]
here it is https://github.com/RobinLinus/snapdrop/issues/215
i'm not sure though how to interpret this...maybe we need to send the goodbye to the server before when the app i closed for good?

**Comment by fm-sys** [comment]
I tried to do that in the `onDestroy` method via leaving the website which works in most cases rather well

**Comment by ueen** [comment]
yea i see, i feel like that doesnt work at all, bacause its to late...

**Comment by ueen** [comment]
hmm..so it does work with
```
@Override
    protected void onStop() {
        webView.loadUrl("about:blank");
        super.onStop();
    }
```

**Comment by ueen** [comment]
Maybe this is only an issue if the app is force closed and reopened, which should be rare under real life conditions, i'll test some more, but i think removing the `cookie` and `loadAgain` is a good idea either way, because they do not fully prevent the app from showing itself and add other bugs.

**Comment by fm-sys** [comment]
> 
> 
> yea i see, i feel like that doesnt work at all, bacause `onDestroy` isnt always called...

Yes, when reinstalling at the emulator it doesn't get called, but under real life conditions it's mostly fine. 

BTW, I really appreciate your continuous work for _Snapdrop for Android_ - reduce the code/maintain complexity and making it better from user perspective. Thanks for your help!

**Comment by ueen** [comment]
sure no problem, this was really bugging me :P
