### ISSUE TITLE
Dark mode broken

### ISSUE THREAD

**Issue by ueen** [fm-sys/snapdrop-android#79]
In the newest play update, the darkmode doesnt seem work anymore, it does work in my PR tough, strange, isn't it?

**Comment by fm-sys** [comment]
For me it still works. Is you're "Android System WebView" up to date?

**Comment by ueen** [comment]
It is, strange, it is working with the debug version  but not the one from google play

**Comment by Krrishdhaneja** [comment]
Hmm it works fine for me, I am running Android 11, but haven't faced any issue yet with dark mode. Btw can you share a screenshot of the dark mode from snapdrop of your phone?

**Comment by ueen** [comment]
https://user-images.githubusercontent.com/5067479/116442945-6084cd00-a853-11eb-86b5-342cf1e5b636.mp4

**Comment by ueen** [comment]
Reinstalled from play, now it works - strange, I'll close it for now.
