### ISSUE TITLE
sending of files between two snapdrop apps seams to be very slow

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#8]
The sending of files between two snapdrop apps seams to be very slow. Looks a bit like RobinLinus/snapdrop#123

**Comment by moriel5** [comment]
I'm not sure whether this is related, or if this is due to issues with my local WiFi that I am still investigation, however sending and receiving between two Android devices, on the same network, with the app installed on both of them, simply does not work, without any notice at all.

**Comment by fm-sys** [comment]
>  sending and receiving between two Android devices, on the same network, with the app installed on both of them, simply does not work, without any notice at all. 

A friend of mine also had that issue. Are you using a wifi repeater or something like that? Snapdrop is unfortunately causing problems with such devices sometimes... :-/

**Comment by moriel5** [comment]
Not at the moment, though I am trying to figure out why similar methods of sharing (such as via direct TCP) are not working for me, despite the fact that my router (Linksys WRT32X) is running OpenWrt, which I had configured to allow these kinds of connections.

**Comment by fm-sys** [comment]
> however sending and receiving between two Android devices, on the same network, with the app installed on both of them, simply does not work, without any notice at all.

This is a larger problem, see https://github.com/RobinLinus/snapdrop/issues/298. Nothing we can do from our side. Let's close here...
