### ISSUE TITLE
ForegroundService

### ISSUE THREAD

**Issue by ueen** [fm-sys/snapdrop-android#87]
What do you think about running a service in order to allow constant communication? Kind of what i'm doing with the Firefox Addon.

Use-Case:
Send something from desktop and recieve pushnotification instead of opening the app.

I dont know how serverly this might affect battery, so it should be optional.

**Comment by fm-sys** [comment]
Sounds good, although I'm not 100% sure how we could archive this within a service...

**Comment by ueen** [comment]
Apparently boy that difficult https://stackoverflow.com/questions/39038771/calling-javascript-from-service-android
But we need to look at for double instances, like app and service...

**Comment by ueen** [comment]
Maybe a service is not feasable, what about push notifications? I found this FOSS solution as i dont really want to use FCM
https://github.com/gotify
as far as i understood another app has to be installed for that and we need to find a host/server, then this could be integrated to my addon to send text&links via gotify, what do you think?

**Comment by fm-sys** [comment]
I would like to keep things simple. gotify is probably a pretty cool open source project, but is IMHO unrelated to Snapdrop so it's probably better to keep them separated. Probably gotify even already have a working windows client (for Android they definitely have).

**Comment by fm-sys** [comment]
I think a foreground service is feasable, although it's probably a bit difficult... Spare time is the most blocking issue 😅

**Comment by ueen** [comment]
Yea you're right, my usecase actually is just send text/links if the app is closed, i thought that might be something to implement in the app, but maybe its easier to do something with the add-on, like adding the option to register a device and then push notifications there. I really dont want FCM in this app.
A foreground service would be possible but really a mess, but it wouldnt require the addon/website to be changed what would be a plus.
Maybe something like this could work https://github.com/pushbits/server, this basically sends notifications via matrix, so if you have Element installed you just get the messages via that (though that is proabably using FCM anyway, but we dont have to).

**Comment by fm-sys** [comment]
I actually like the idea of a snapdrop foreground service, but the foreground notification should provide the possibility to easily stop the service.

**Comment by ueen** [comment]
yea would definitely disable by default, but do you know about battery consumtion? This is a absolute convenience use case that i maybe use every 2d, so i woudnt sacrifice battery life for it, also i think it would be really hard to seperate the service snapdrop client and the android client, which will lead to even more headach with the app showing itself and the service...

or we shift everything to the service and only use the app as a frontend and do the networking via the service? Not sure how this would work, but this could solve the showing it self issue, as theres always a single service running - dont know if this would be possible and we have to look out for the battery, do you ahve any experience with this?

So i guess im somewhat leaning towards and already existing FOSS push solution like via matrix.

**Comment by ueen** [comment]
i contacted silkky.cloud and they would be willing to host pushbits, so i think i'll be going with the addon->matrix bridge for the sending text/links usecase, i think a foreground service would be to battery costly, so i'm closing for know, feel free to reopen if you would think its still feasible :)

**Comment by ueen** [comment]
Hmm looked into it way longer than I should have, matrix also doesn't seem to be feasible, so I think that's it, I'll have to live with this minor inconvenience.
Or the foreground service but I'm really not sure if it's worth the battery drain or how bad it would be...
