### ISSUE TITLE
Should we update to storage 0.6.0?

### ISSUE THREAD

**Issue by fm-sys** [fm-sys/snapdrop-android#90]
#89 bumps storage from 0.5.3 to 0.6.0. However, some more adoptions seem to be necessary to get it running. Should we update to this version?

**Comment by ueen** [comment]
Ah I see, we can leave it at 0.5.3 for now if there are no issues I guess 😊

**Comment by anggrayudi** [comment]
We can close this issue since the storage version has been updated to `0.9.0`. See PR #106.

**Comment by fm-sys** [comment]
Yes, you are right. Thanks for the hint 👍
