### ISSUE TITLE
Snapdrop usually freezes

### ISSUE THREAD

**Issue by aha999** [fm-sys/snapdrop-android#92]
**Describe the bug**
Usually when i try to share a file and select the device that i'm going to be sending to, SnapDrop freezes.

**To Reproduce**
1. Select a file in the app/gallery
2. Click on share via Snapdrop
3. Snapdrop opens
4. select the device that you want to send to, and animation freezes

**Expected behavior**
it should send the file or ask to send the file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 6
 - OS: Android 11 (stock)
 - Browser Firefox
 - Version 1.6.0

**Additional context**
Sometimes it starts working if i go into the menu and back...

**Comment by fm-sys** [comment]
v1.7.0 was released just some days ago. Could you please try if the issue still exists?

Furthermore, could you test if sending the files does work via browser (https://snapdrop.net)?

**Comment by ueen** [comment]
If you mean the background wave animation, it actually is stopping if another device is detected, that's no sign of the app freezing or crashing :)

**Comment by aha999** [comment]
Yes, when it finds the device, the animation stops, but other functions are available (sorry for my mistake), and i can't send the file by clicking. First i have to refresh again, and then i can click to send the file.

**Comment by ueen** [comment]
yea sometimes a refresh is needed, but the the animation is the expected behaviour from snapdrop.net.
If thats it, please close :)
