### ISSUE TITLE
Custom save location

### ISSUE THREAD

**Issue by anggrayudi** [fm-sys/snapdrop-android#93]
The default location for Snapdrop is `Download`. But as a user, it is better if I can select a custom directory to save downloaded files, e.g. `Video`, `Received`, or `Snapdrop`. I don't want to mix `Download`'s content with the files downloaded from Chrome, Firefox, etc. I hope this feature will be added to Snapdrop settings. BTW, it could be easier on scoped storage if you use [`SimpleStorageHelper`](https://github.com/anggrayudi/SimpleStorage#simplestoragehelper) to pick the save location.

**Comment by fm-sys** [comment]
> BTW, it could be easier on scoped storage if you use [`SimpleStorageHelper`](https://github.com/anggrayudi/SimpleStorage#simplestoragehelper) to pick the save location.

AFAIK, the strings are always in English. Any plan to translate these strings or even better offer the option to provide own resource strings to `simplestoragehelper`?

**Comment by anggrayudi** [comment]
Actually, you can override all strings used in `SimpleStorageHelper`.
https://stackoverflow.com/q/4263259/3922207

**Comment by fm-sys** [comment]
Oh, that's cool. Didn't know that. Will do as soon as I find time :)
