### ISSUE TITLE
Can't receive messages neither from PC or phone

### ISSUE THREAD

**Issue by lukepushsolo** [fm-sys/snapdrop-android#97]
I have a Pixel XL and Windows Chome.
Sending files to each device is OK, but messages can't be received. Nothing happens even no failure notification.

**Comment by ueen** [comment]
There are some issues, like sending between Mac and Android, but this is due to the website and the implementation of the browsers https://github.com/RobinLinus/snapdrop

Try snapdrop.net in your browser, if it doesnt work there, its not a problem with this app :)

**Comment by fm-sys** [comment]
Can you try to use https://snapdrop.net on your pixel smartphone? Does it work in this case or is it a general issue?

**Comment by lukepushsolo** [comment]
> Can you try to use https://snapdrop.net on your pixel smartphone? Does it work in this case or is it a general issue?

Not a usual issue. It seems to be correlated with LAN's condition. I tried connecting to a different WIFI and the issue didn't show up.

**Comment by fm-sys** [comment]
If the problem shows up even without using the android app, the issue should be opened here:

https://github.com/RobinLinus/snapdrop/issues

it's kina hard to help you here currently without having more information... Maybe the situation will get better as soon as  #71 is implemented.

**Comment by lukepushsolo** [comment]
> If the problem shows up even without using the android app, the issue should be opened here:
> 
> https://github.com/RobinLinus/snapdrop/issues
> 
> it's kina hard to help you here currently without having more information... Maybe the situation will get better as soon as #71 is implemented.

I'll be keeping up to following it. Sadly, I can't reproduce this bug while it happens randomly.

**Comment by fm-sys** [comment]
Yes, we know that quite some users are affected by such issues but unfortunately we can't do anything about it. The only one who might be able to solve this are the guys of https://snapdrop.net/.

There are some issues open on their side, e.g.:

https://github.com/RobinLinus/snapdrop/issues/113
https://github.com/RobinLinus/snapdrop/issues/194

Long story short, I think we can close this issue...
